### ISSUE TITLE
DescribePrice接口问题

### ISSUE THREAD

**Issue by opstrip** [aliyun/aliyun-openapi-python-sdk#101]
调用 DescribePrice sdk 接口和 API 的 DescribePrice 都报“Error:InvalidAction Specified action is not valid.”错误。请问下是这个接口还不能用吗？
<img width="670" alt="aliyuncli" src="https://user-images.githubusercontent.com/14342611/43573777-207f7450-9675-11e8-914d-197607707ff0.png">

**Comment by Qingtang-SDK** [comment]
Please use the newest version of CLI:  https://help.aliyun.com/product/29991.html
