### ISSUE TITLE
Issues while creating Kubernetes cluster 

### ISSUE THREAD

**Issue by jyoti-26** [aliyun/aliyun-openapi-python-sdk#106]
**The code structure for creating k8s cluster**

from aliyunsdkcore import client
from aliyunsdkcs.request.v20151215 import CreateClusterRequest
try:
        # Init
        clt = client.AcsClient(ak=ak, secret=sk, region_id=region_id)

        # Setting Params
    request = CreateClusterRequest.CreateClusterRequest()
    request.add_body_params('Maid', 60)
    request.add_body_params('Name','my-test-Kubernetes-cluster')
    request.add_body_params('region_id', 'cn-hongkong')
    request.add_body_params('zoneid', 'cn-hongkong-b')
    request.add_body_params('cluster_type', 'Kubernetes')
    request.add_body_params('vpcid','vpc-j6cuyh9068odtesp0fc2c')
    request.add_body_params('vswitchid', 'vsw-j6cd85s66stm5bhmbhwd3')
    request.add_body_params('num_of_nodes', 1)
    request.add_body_params('container_cidr', '172.16.0.0/16')
    request.add_body_params('service_cidr', '172.16.0.0/20')
    request.add_body_params('cloud_monitor_flags', True)
    request.add_body_params('master_instance_type', 'ecs.sn1ne.large')
    request.add_body_params('master_system_disk_category', 'cloud_efficiency')
    request.add_body_params('master_system_disk_size', 40)
    request.add_body_params('worker_instance_type', 'ecs.sn1ne.large')
    request.add_body_params('worker_system_disk_category', 'cloud_efficiency')
    request.add_body_params('snat_entry', True)
    request.add_body_params('ssh_flags', True)
    request.add_body_params('login_password', 'Hello1234')
# Sending Request
        request.set_accept_format('json')
        response = clt.do_action_with_exception(request)

        print response
except Exception as ex:
    print(ex)

Facing issues are as follows

I am RAM user

SDK calling is proper working for DeleteClusterRequest, DescribeClusterDetailRequest 
but when it comes to creating k8s cluster I am getting below  ERROR

**HTTP Status: 400 Error:SDK.UnknownServerError {"code":"ErrorValidateParameters","message":"Missing network type","requestId":"F1F07A8D-47E5-40DB-8F54-C81C1D1961A8","status":400} RequestID: None**

I have set all the body parameter required for the creating cluster

Kindly help us.

**Comment by Qingtang-SDK** [comment]
Please file a work order for this issue.  https://workorder-intl.console.aliyun.com/console.htm?spm=a2c63.p38356.0.dcontactus3.263749d7zCLz1v#/ticket/createIndex
