### ISSUE TITLE
DescribeEipAddresses 这个接口和文档定义不一致

### ISSUE THREAD

**Issue by rsonghuster** [aliyun/aliyun-openapi-python-sdk#108]
https://help.aliyun.com/document_detail/36018.html?spm=a2c4g.11186623.6.610.6dd66780R6CV6t
https://github.com/aliyun/aliyun-openapi-python-sdk/blob/master/aliyun-python-sdk-ecs/aliyunsdkecs/request/v20140526/DescribeEipAddressesRequest.py

按照文档定义，应该有set_RegionId 这个接口吧

**Comment by Qingtang-SDK** [comment]
产品API定义层面问题请参考阿里云文档，或者发工单，谢谢。
