### ISSUE TITLE
aliyun-python-sdk-cbn in JP region

### ISSUE THREAD

**Issue by makotaka** [aliyun/aliyun-openapi-python-sdk#116]
I think pypi cache server in Alibaba Cloud JP region is still not updated and we cannot install  aliyun-python-sdk-cbn into a server on Japan region by pip install.
I know that I can install it by commenting out all lines of ~/.pip/pip.conf, but I think you should update cache server in the region.

BR!

**Comment by Qingtang-SDK** [comment]
Hi,  @makotaka  Thanks for your feedback. It's a very interesting issue, and we are sorry that we can not reproduce it in our JP region ECS server. Could you show us more information (i.e. your configuration details excluding confidential keys) so we can try to reproduce it again?

**Comment by makotaka** [comment]
Today I tried again and it seems to be resolved. Thanks!

**Comment by Qingtang-SDK** [comment]
Our SDK packages are hosted on PYPI and that might be some connection problems between JP region and US.  Glad your issue has gone. Welcome to contact us if you have any other problem. Have a nice day!
