### ISSUE TITLE
使用ScaleClusterRequest接口伸缩集群报错

### ISSUE THREAD

**Issue by liuzhi1986** [aliyun/aliyun-openapi-python-sdk#121]
使用ScaleClusterRequest接口伸缩集群报错
代码如下：
```
from aliyunsdkcore.client import AcsClient
from aliyunsdkcs.request.v20151215 import ScaleClusterRequest


client = AcsClient('access key', 'access secret', 'cn-hangzhou')

request = ScaleClusterRequest.ScaleClusterRequest()
request.set_ClusterId('clusterid')
body = '''{
    'disable_rollback': True,
    'timeout_mins': 60,
    'worker_instance_type': 'ecs.n1.xlarge',
    'num_of_nodes': 4
}'''
request.set_method('PUT')
request.set_content(body)
response = client.do_action_with_exception(request)

print(response)
```

错误信息：
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 500 Error:SDK.UnknownServerError Can not parse error message from server response. RequestID: None

使用do_action(request)报错信息如下：
b'code=415, message=Unsupported Media Type\n'

**Comment by cheyang** [comment]
请开一个阿里云工单，并且提供一下Kubernetes的集群id。谢谢。

**Comment by Qingtang-SDK** [comment]
您好， Unsupported Media Type 这个错误是CS（容器服务）这个产品的具体报错，请参照具体的产品文档； 如仍有问题请发工单。在您的反馈中，我们也发现CS产品在API出错时的信息是不规范的，导致SDK未能正常显示，我们已经把问题反馈给CS团队。@cheyang

给您造成不便，我们深感抱歉。有问题随时联系我们。感谢！
