### ISSUE TITLE
使用AcsClient请求接口的时候报错

### ISSUE THREAD

**Issue by Rangerkriby** [aliyun/aliyun-openapi-python-sdk#124]
aliyunsdkcore.client.AcsClient不能使用了吗，使用AcsClient请求接口的时候报错
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 400 Error:MissingParameter The input parameter "Key" that is mandatory for processing this request is not supplied

**Comment by wallisyan01** [comment]
您好？根据您提供的错误信息，您是否传递了必要的参数，比如access_key_id，access_key_secret以及region_id。常见的调用如下
clt = client.AcsClient(access_key_id, access_key_secret, region_id)
