### ISSUE TITLE
no BatchSetCdnDomainConfig request

### ISSUE THREAD

**Issue by dading** [aliyun/aliyun-openapi-python-sdk#126]
1. In aliyun-python-sdk-cdn v20180510 package missing BatchSetCdnDomainConfig.py

**Comment by Qingtang-SDK** [comment]
Hi,  please use  aliyunsdkcdn/request/v20180510/BatchSetCdnDomainConfigRequest.py in newest version of aliyun-python-sdk-cdn. 

e.g. Try: ```  from aliyunsdkcdn.request.v20180510.BatchSetCdnDomainConfigRequest as BatchSetCdnDomainConfigRequest ```
