### ISSUE TITLE
Specified api is not found with QueryInstanceGaapCostRequest 

### ISSUE THREAD

**Issue by Martwu** [aliyun/aliyun-openapi-python-sdk#129]
> Traceback (most recent call last):
>   File "main.py", line 12, in <module>
>     data = bill.get_monthly(2018, 10)
>   File "/Users/coolxwu/Desktop/Projects/JZDY-PG/console_clouds/cloudcsl/sdks/aliyun/bill.py", line 18, in get_monthly
>     print(_get_data(req_bill))
>   File "/Users/coolxwu/Desktop/Projects/JZDY-PG/console_clouds/cloudcsl/sdks/aliyun/__init__.py", line 24, in _get_data
>     result = json.loads(client.do_action_with_exception(req_func))
>   File "/Users/coolxwu/Desktop/Projects/JZDY-PG/console_clouds/venv/lib/python3.7/site-packages/aliyunsdkcore/client.py", line 277, in do_action_with_exception
>     request_id=request_id)
> aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 404 Error:InvalidApi.NotFound Specified api is not found, please check your url and method. RequestID: 05E17A7B-C88F-42F0-9A51-AD3EE19CE5FD

Exception as above

**Comment by DearXXD** [comment]
无解  放弃SDK

**Comment by JacksonTian** [comment]
@DearXXD 请问是一样的问题吗

**Comment by Qingtang-SDK** [comment]
您好，对于这个问题，是由于之前的bssopenapi需要开通产品后再使用API导致的。若未开通，则会遇到 InvalidApi.NotFound 错误。这个问题现在已经修正，bssopenapi现在不需要开通动作就能访问API。您以后不会再遇到 bssopenapi 的相同问题了。

给您造成的不便深感抱歉，感谢您的反馈。
