### ISSUE TITLE
acs sdk无法打包

### ISSUE THREAD

**Issue by hitme** [aliyun/aliyun-openapi-python-sdk#13]
执行sdk打包命令 ./setup.py bdist_egg 输出如下错误：
| => ./setup.py bdist_egg
running bdist_egg
running egg_info
creating aliyun_python_sdk_acs.egg-info
writing requirements to aliyun_python_sdk_acs.egg-info/requires.txt
writing aliyun_python_sdk_acs.egg-info/PKG-INFO
writing top-level names to aliyun_python_sdk_acs.egg-info/top_level.txt
writing dependency_links to aliyun_python_sdk_acs.egg-info/dependency_links.txt
writing manifest file 'aliyun_python_sdk_acs.egg-info/SOURCES.txt'
reading manifest file 'aliyun_python_sdk_acs.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'aliyun_python_sdk_acs.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.12-intel/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/aliyunsdkacs
copying aliyunsdkacs/__init__.py -> build/lib/aliyunsdkacs
creating build/lib/aliyunsdkacs/request
copying aliyunsdkacs/request/__init__.py -> build/lib/aliyunsdkacs/request
creating build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/__init__.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/DeleteApiRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/DeleteControlPolicyRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/DeleteFlowControlRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/DeletePolicyRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/DeleteProductRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/DeleteTairCacheRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/DeleteVersionRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/GetApiBackupListRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/GetApiBackupRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/GetApiNewRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/GetApiRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/GetControlPolicyRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/GetGlobalRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/GetProductRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/GetTairCacheRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/GetVersionRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutApiErrorMappingRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutApiNewRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutApiParametersRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutApiReleaseRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutApiRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutApiResultMappingRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutApiRollbackRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutApiStatusRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutApiVisibilityRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutControlPolicyRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutFlowControlRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutGlobalErrorMappingRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutPolicyRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutProductRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutVersionErrorMappingRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutVersionParametersRequest.py -> build/lib/aliyunsdkacs/request/v20150101
copying aliyunsdkacs/request/v20150101/PutVersionRequest.py -> build/lib/aliyunsdkacs/request/v20150101
creating build/lib/aliyunsdkacs/request/v20150201
copying aliyunsdkacs/request/v20150201/__init__.py -> build/lib/aliyunsdkacs/request/v20150201
copying aliyunsdkacs/request/v20150201/ApiFlowControlRequest.py -> build/lib/aliyunsdkacs/request/v20150201
creating build/bdist.macosx-10.12-intel
creating build/bdist.macosx-10.12-intel/egg
creating build/bdist.macosx-10.12-intel/egg/aliyunsdkacs
copying build/lib/aliyunsdkacs/__init__.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs
creating build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request
copying build/lib/aliyunsdkacs/request/__init__.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request
creating build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/__init__.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/DeleteApiRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/DeleteControlPolicyRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/DeleteFlowControlRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/DeletePolicyRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/DeleteProductRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/DeleteTairCacheRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/DeleteVersionRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/GetApiBackupListRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/GetApiBackupRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/GetApiNewRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/GetApiRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/GetControlPolicyRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/GetGlobalRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/GetProductRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/GetTairCacheRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/GetVersionRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutApiErrorMappingRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutApiNewRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutApiParametersRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutApiReleaseRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutApiRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutApiResultMappingRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutApiRollbackRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutApiStatusRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutApiVisibilityRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutControlPolicyRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutFlowControlRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutGlobalErrorMappingRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutPolicyRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutProductRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutVersionErrorMappingRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutVersionParametersRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
copying build/lib/aliyunsdkacs/request/v20150101/PutVersionRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101
creating build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150201
copying build/lib/aliyunsdkacs/request/v20150201/__init__.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150201
copying build/lib/aliyunsdkacs/request/v20150201/ApiFlowControlRequest.py -> build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150201
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/DeleteApiRequest.py to DeleteApiRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/DeleteControlPolicyRequest.py to DeleteControlPolicyRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/DeleteFlowControlRequest.py to DeleteFlowControlRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/DeletePolicyRequest.py to DeletePolicyRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/DeleteProductRequest.py to DeleteProductRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/DeleteTairCacheRequest.py to DeleteTairCacheRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/DeleteTairCacheRequest.py", line 34
    def get_x-acs-cache-key(self):
             ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/DeleteVersionRequest.py to DeleteVersionRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetApiBackupListRequest.py to GetApiBackupListRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetApiBackupRequest.py to GetApiBackupRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetApiNewRequest.py to GetApiNewRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetApiRequest.py to GetApiRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetControlPolicyRequest.py to GetControlPolicyRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetGlobalRequest.py to GetGlobalRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetProductRequest.py to GetProductRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetTairCacheRequest.py to GetTairCacheRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetTairCacheRequest.py", line 34
    def get_x-acs-cache-key(self):
             ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/GetVersionRequest.py to GetVersionRequest.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiErrorMappingRequest.py to PutApiErrorMappingRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiErrorMappingRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiNewRequest.py to PutApiNewRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiNewRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiParametersRequest.py to PutApiParametersRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiParametersRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiReleaseRequest.py to PutApiReleaseRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiReleaseRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiRequest.py to PutApiRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiResultMappingRequest.py to PutApiResultMappingRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiResultMappingRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiRollbackRequest.py to PutApiRollbackRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiRollbackRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiStatusRequest.py to PutApiStatusRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiStatusRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutApiVisibilityRequest.py to PutApiVisibilityRequest.pyc
Sorry: IndentationError: expected an indented block (PutApiVisibilityRequest.py, line 55)
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutControlPolicyRequest.py to PutControlPolicyRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutControlPolicyRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutFlowControlRequest.py to PutFlowControlRequest.pyc
Sorry: IndentationError: expected an indented block (PutFlowControlRequest.py, line 55)
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutGlobalErrorMappingRequest.py to PutGlobalErrorMappingRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutGlobalErrorMappingRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutPolicyRequest.py to PutPolicyRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutPolicyRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutProductRequest.py to PutProductRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutProductRequest.py", line 40
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutVersionErrorMappingRequest.py to PutVersionErrorMappingRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutVersionErrorMappingRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutVersionParametersRequest.py to PutVersionParametersRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutVersionParametersRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutVersionRequest.py to PutVersionRequest.pyc
  File "build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150101/PutVersionRequest.py", line 34
    def get_Content-Type(self):
                   ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150201/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.12-intel/egg/aliyunsdkacs/request/v20150201/ApiFlowControlRequest.py to ApiFlowControlRequest.pyc
creating build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying aliyun_python_sdk_acs.egg-info/PKG-INFO -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying aliyun_python_sdk_acs.egg-info/SOURCES.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying aliyun_python_sdk_acs.egg-info/dependency_links.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying aliyun_python_sdk_acs.egg-info/requires.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
copying aliyun_python_sdk_acs.egg-info/top_level.txt -> build/bdist.macosx-10.12-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/aliyun_python_sdk_acs-0.0.2-py2.7.egg' and adding 'build/bdist.macosx-10.12-intel/egg' to it
removing 'build/bdist.macosx-10.12-intel/egg' (and everything under it)

**Comment by gaort** [comment]
@hitme 
您好，感谢您的反馈，十分抱歉这么久才回复您，请问您现在问题解决了吗？
