### ISSUE TITLE
aliyunsdkbssopenapi调取方式有什么不同吗？是否给出实例

### ISSUE THREAD

**Issue by Alicealpha** [aliyun/aliyun-openapi-python-sdk#132]
from aliyunsdkcore import client
from aliyunsdkbssopenapi.request.v20171214 import QueryMonthlyInstanceConsumptionRequest
  request = QueryMonthlyInstanceConsumptionRequest.QueryMonthlyInstanceConsumptionRequest()
    request.set_accept_format('json')
    request.set_method('POST')
    request.set_version('2017-12-14')
    request.set_action_name('QueryMonthlyInstanceConsumption')
    request.add_query_param('BillingCycle','2018-10')
    request.add_query_param('PageSize', '100')
    clt = client.AcsClient(key, secret)
    response = clt.do_action(request)
    print(str(response, encoding='utf-8'))
错误信息如下：
{"Recommend":"https://error-center.aliyun.com/status/search?Keyword=InvalidApi.NotFound&source=PopGw","Message":"Specified api is not found, please check your url and method.","RequestId":"3EDAF763-B9A4-44AD-971E-46E53511344F","HostId":"business.aliyuncs.com","Code":"InvalidApi.NotFound"}

**Comment by wallisyan01** [comment]
Thanks for your feedback. It's a very interesting issue, and we are sorry that we can not reproduce it. Could you show us more information

**Comment by Qingtang-SDK** [comment]
@Alicealpha  您好，我们正在调取服务端日志来查看您遇到的问题，感谢您的反馈

**Comment by Qingtang-SDK** [comment]
您好，对于这个问题，是由于之前的bssopenapi需要开通产品后再使用API导致的。若未开通，则会遇到 InvalidApi.NotFound 错误。这个问题现在已经修正，bssopenapi现在不需要开通动作就能访问API。您以后不会再遇到 bssopenapi 的相同问题了。

给您造成的不便深感抱歉，感谢您的反馈。
