### ISSUE TITLE
pipenv install aliyun-python-sdk-core-v3

### ISSUE THREAD

**Issue by ninjacn** [aliyun/aliyun-openapi-python-sdk#136]
UnsupportedPythonVersion: aliyun-python-sdk-core requires Python '<3' but the running Python is 3.7.1

**Comment by wallisyan01** [comment]
I suggest that you use `pipenv install aliyun-python-sdk-core-v3` again. Because I tried, it seems to be OK.

**Comment by JacksonTian** [comment]
Hi @ninjacn , Is the problem exist also?

**Comment by ninjacn** [comment]
Python版本换3.6了
