### ISSUE TITLE
使用CommonRequest调用企业级分布式应用服务 EDAS提供的API 接口（请求指导）

### ISSUE THREAD

**Issue by guomingui** [aliyun/aliyun-openapi-python-sdk#137]
代码如下：
from aliyunsdkcore.client import AcsClient
from aliyunsdkcore.request import CommonRequest

client = AcsClient(
           "LTAI1*********N1",
           "BW7*********************VtT94dLO",
           "cn-beijing"
        )

request = CommonRequest()
# 查询一台或多台实例的详细信息(云服务器 ECS)
# request = CommonRequest(domain='ecs.aliyuncs.com', version='2014-05-26', action_name='DescribeInstances')
# 获取应用列表(企业级分布式应用服务 EDAS)
request = CommonRequest(domain='edas-vpc.cn-beijing.aliyuncs.com', version='2017-08-01', action_name='ListApplicationRequest')

request.add_query_param('PageNumber', '1')
request.add_query_param('PageSize', '1')
response = client.do_action_with_exception(request)

错误：
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 400 Error:MissingDate Date is mandatory for this action. RequestID: 43EC3A0F-C987-43CF-A3E2-DDC49F3F3095

查询一台或多台实例的详细信息(云服务器 ECS)是没有问题的， 获取应用列表(企业级分布式应用服务 EDAS)一直失败，我不知道是什么原因，不知道是否是参数（domain、action_name）错误的原因，技术有限，请求解惑！

**Comment by wallisyan01** [comment]
建议您直接使用edas的api，代码如下：
```
from aliyunsdkedas.request.v20170801.ListApplicationRequest import ListApplicationRequest
request = ListApplicationRequest()
response = client.do_action_with_exception(request)
```
如果您坚持使用CommonRequest，我建议您可以按照如下的案例进行测试：
```
request = CommonRequest(domain='edas-vpc.cn-beijing.aliyuncs.com', version='2017-08-01', action_name='ListApplication')
request.set_uri_pattern('/pop/v5/app/app_list')
request.set_method('POST')
response = client.do_action_with_exception(request)
```

**Comment by guomingui** [comment]
非常感谢您，问题已经解决了。

在 2018-12-17 18:09:22，"wallisyan01" <notifications@github.com> 写道：


建议您直接使用edas的api，代码如下：

from aliyunsdkedas.request.v20170801.ListApplicationRequest import ListApplicationRequest

request = ListApplicationRequest()

response = client.do_action_with_exception(request)



如果您坚持使用CommonRequest，我建议您可以按照如下的案例进行测试：

request = CommonRequest(domain='edas-vpc.cn-beijing.aliyuncs.com', version='2017-08-01', action_name='ListApplication')

request.set_uri_pattern('/pop/v5/app/app_list')

request.set_method('POST')

response = client.do_action_with_exception(request)

**Comment by JacksonTian** [comment]
Thanks @wallisyan01
