### ISSUE TITLE
[Feature Request] Add QueryMetricMeta and QueryProjectMeta in cms APIs

### ISSUE THREAD

**Issue by aylei** [aliyun/aliyun-openapi-python-sdk#142]
It will be useful if the sdk could add these two APIs: 

documentations: 
https://help.aliyun.com/document_detail/98846.html?spm=a2c4g.11186623.6.675.239b5679PxCll0
https://help.aliyun.com/document_detail/98866.html?spm=a2c4g.11186623.6.674.7c1d6e3ewnmpAc

**Comment by JacksonTian** [comment]
Hello, I will tell the product team to release new version SDK. Thank you very much.

**Comment by aylei** [comment]
@JacksonTian Thanks for your quick response! Should I close the PR?

**Comment by JacksonTian** [comment]
Yes. You can use the code in your project temporary before the new SDK released.
