### ISSUE TITLE
提供一个demo吧

### ISSUE THREAD

**Issue by wooodyhuang** [aliyun/aliyun-openapi-python-sdk#15]
集成的成本太高了，建议提供一个demo，可以节省许多的时间，让这个库变得更有价值。

**Comment by qianlifu12345** [comment]
我也赞同，没有看到完整的python 的文档

**Comment by qianlifu12345** [comment]
我看了下阿里云python sdk 其实就是将open api进行了封装。
这里有代码示例
https://help.aliyun.com/document_detail/51172.html?spm=5176.doc61259.6.784.WYqK6u

其实想调用相应的功能可以先去查找open api的文档，然后去找sdk相应的类。open api 里请求的参数可以set在request里进行请求。

**Comment by gaort** [comment]
@wooodyhuang @qianlifu12345 
十分感谢您的反馈，十分抱歉这么久才回复您
目前阿里云python sdk的文档集中在官网进行提供，包含您需要的demo等信息
具体的链接地址为：
https://help.aliyun.com/document_detail/53090.html?spm=5176.136436.698463.7.40500caflQ6gIQ
