### ISSUE TITLE
增加对 http client 的 test cases

### ISSUE THREAD

**Issue by JacksonTian** [aliyun/aliyun-openapi-python-sdk#157]
包含但不限于： 跳转行为， TCP_NO_DELAY flag的设置，Connection 这个header 等等

**Comment by Qingtang-SDK** [comment]
@wallisyan 
1，跳转行为已经确认关闭；
2，TCP_NO_DELAY  未设置，但这是性能影响，待性能需要提升时再做
3，Connection Header默认情况下未设置，
4，requests的retry确认关闭
5， requests的timeout确认设置正确
