### ISSUE TITLE
能否规范所有的sdk返回的固有的key值，以便于我们抽象兼容。

### ISSUE THREAD

**Issue by mianbao-cn-com** [aliyun/aliyun-openapi-python-sdk#162]
其他的模块都非常的好，一直到今天用到了bssopenapi.....，返回的结果跟别的层级结构不一样，常用的翻页的key与其他的sdk返回也不一样....
bssopenapi的返回结果如下：
================================
{u'Code': u'Success',
 u'Data': {u'BillingCycle': u'2018-12',
           u'Items': {u'Item': []
u'PageNum': 1,
           u'PageSize': 20,
           u'TotalCount': 665},
================================
而其他的API有定式的规范，使我们能够更好的调用：
{u'Instances': {u'KVStoreInstance': []
 u'PageNumber': 1,
 u'PageSize': 30,
 u'RequestId': u'E8E7981E-3F8F-4604-A7BA-62CA6969CE60',
 u'TotalCount': 51}

**Comment by Qingtang-SDK** [comment]
您好，这个问题是 bssopenapi 这个产品的接口定义是这样导致的。SDK目前只是返回给您服务端的响应。

这个问题已经反馈到 bssopenapi 产品团队，他们已经收到这个问题，并计划在 bssopenapi 中的所有接口都新增一个 PageNumber 参数，预计问题解决的时间点是： 2019年3月31日。

在此之前，还是得麻烦您在代码中做一些判断和适配。感谢您的反馈，给您造成的不便我们深感抱歉，欢迎您继续反馈其他问题，谢谢！
