### ISSUE TITLE
client.py的_parse_error_info_from_response_body解析JSON的问题

### ISSUE THREAD

**Issue by eaglesbest** [aliyun/aliyun-openapi-python-sdk#165]
client.py的第244行，传递进来的response_body在python3上是byte类型，但是没有进行解码，在python版本上，json库可以直接loads byte类型的数据；但是在python3.5.2版本上json库不能loads byte类型的数据，导致报TypeError异常，但是没有捕捉，导致报错；
建议在处理response_boyd时都进行decode处理，以便兼容

**Comment by wallisyan** [comment]
感谢您的反馈。这个问题，在client.py的272行已经进行了处理

**Comment by Qingtang-SDK** [comment]
@wallisyan  请看一下这个问题

**Comment by wallisyan** [comment]
感谢您的反馈，这个问题在2.11.4版本已经修复。建议您升级到最新版本或者修改client.py代码
`server_error_code, server_error_message = self._parse_error_info_from_response_body(body)`为`server_error_code, server_error_message =self._parse_error_info_from_response_body(body.decode('utf-8'))`

**Comment by eaglesbest** [comment]
好的，看到已经修改了，谢谢
