### ISSUE TITLE
aliyun-python-sdk-core-v3 依赖配置有问题, 漏了 jmespath

### ISSUE THREAD

**Issue by gtxx3600** [aliyun/aliyun-openapi-python-sdk#166]
[Python 3 version requirements ](https://github.com/aliyun/aliyun-openapi-python-sdk/blob/6640626a3f6d5d1ff8006b5097a802aec492202b/aliyun-python-sdk-core/setup3.py#L49)

[Python 2 version requirements ](https://github.com/aliyun/aliyun-openapi-python-sdk/blob/6640626a3f6d5d1ff8006b5097a802aec492202b/aliyun-python-sdk-core/setup.py#L49)

导致 import 失败, 手动安装 jmespath 可解决
![image](https://user-images.githubusercontent.com/261867/51071585-652b1480-168e-11e9-895c-fe0f19f04dc2.png)

**Comment by Qingtang-SDK** [comment]
谢谢您的反馈，最新版 2.11.1 已经解决了这个问题。对给您造成的不便，我们深感抱歉。再次感谢！
