### ISSUE TITLE
About MessageService Module

### ISSUE THREAD

**Issue by mosuke5** [aliyun/aliyun-openapi-python-sdk#17]
Hi!
I want to use MessageSerevice by python sdk.
but I didn't find MessageService module.
Do you have official MessageService sdk?

**Comment by gaort** [comment]
hi，dear @mosuke5 
thanks for your feedback!
do you mean MessageNotifyService(MNS)?
if yes, the sdk is not included in this repo, you can get it from here:
https://help.aliyun.com/document_detail/32305.html?spm=5176.product27412.6.656.u4gcvw
