### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by chenzheng102** [aliyun/aliyun-openapi-python-sdk#173]
aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.HttpError [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
Endpoint: sts.aliyuncs.com
Product: Sts
SdkCoreVersion: 2.12.0

**Comment by Qingtang-SDK** [comment]
您好，可否请您提供一下具体的调用代码，或者出错的堆栈信息呢？
