### ISSUE TITLE
竟然不支持世界上最好的两门语言中的一门

### ISSUE THREAD

**Issue by zyongqing** [aliyun/aliyun-openapi-python-sdk#18]
为啥不能支持一下 py3 呢？

**Comment by liuyangc3** [comment]
有个目录 python-sdk-core-v3  就是py3的

**Comment by gaort** [comment]
@zyongqing 非常感谢您的反馈
也非常感谢@liuyangc3 的回复，现在已全面支持python3，相关代码在core-v3中
