### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by fantix** [aliyun/aliyun-openapi-python-sdk#2]
As title in late 2015, would be good to support Python 3.3 and above.

**Comment by yfwz100** [comment]
It seems that it support python 3.3 , according to info listed in setup file.

**Comment by fantix** [comment]
No it doesn't according to `2to3` script, some of the results:

```diff
diff --git a/aliyun-python-sdk-core/aliyunsdkcore/http/format_type.py b/aliyun-python-sdk-core/aliyunsdkcore/http/format_type.py
index d24652c..7190b08 100644
--- a/aliyun-python-sdk-core/aliyunsdkcore/http/format_type.py
+++ b/aliyun-python-sdk-core/aliyunsdkcore/http/format_type.py
@@ -42,11 +42,11 @@ def map_accept_to_format(accept):
     return RAW
 
 if __name__ == "__main__":
-    print map_format_to_accept(XML)
-    print map_format_to_accept(JSON)
-    print map_format_to_accept(RAW)
-    print map_accept_to_format("application/xml")
-    print map_accept_to_format("text/xml")
-    print map_accept_to_format("application/json")
+    print(map_format_to_accept(XML))
+    print(map_format_to_accept(JSON))
+    print(map_format_to_accept(RAW))
+    print(map_accept_to_format("application/xml"))
+    print(map_accept_to_format("text/xml"))
+    print(map_accept_to_format("application/json"))
 
 
```

**Comment by Qingtang-SDK** [comment]
Thanks, @fantix  We will take your advice to serious consideration.

**Comment by fantix** [comment]
@Qingtang-SDK looking forward to it

**Comment by useyourfeelings** [comment]
@Qingtang-SDK 请问python3版本在最近计划内吗？急用，特别是aliyun-python-sdk-iot。

**Comment by guanxudong** [comment]
+1

**Comment by fredliang44** [comment]
https://github.com/fredliang44/aliyunsdkcore-python3
I tried to transplant it to python3
I checked it on aliyun-python-sdk-ecs
and it might works on other sdks.

**Comment by sunadm** [comment]
很奇怪，为什么到现在还不支持 Python3，难道这个SDK只是给你们自娱自乐的？

**Comment by Qingtang-SDK** [comment]
@sunadm @useyourfeelings 谢谢两位的反馈，我们的Python 3 SDK正在研发，预计8月底上线。如果您有紧急需求，请欢迎直接联系我们 haowei.yao@alibaba-inc.com，我们会优先解决您的问题。

**Comment by John60676** [comment]
目前已经是2017年10月份了，python3还是不支持

**Comment by gaort** [comment]
现已全面支持python3,  官网使用手册已更新
相关支持的代码在core-v3目录
