### ISSUE TITLE
怎么还没有NAS的相关API啊.

### ISSUE THREAD

**Issue by zhujinhe** [aliyun/aliyun-openapi-python-sdk#21]
现在集成到我们系统中,但是传统网络下的一个NAS配置规则还得手动处理.
不能挂载NAS盘,业务跑不了啊.
赶紧推出NAS盘的API吧.
赶紧推出NAS盘的API吧.
赶紧推出NAS盘的API吧.

**Comment by gaort** [comment]
@zhujinhe 感谢您的反馈，十分抱歉这么久才回复您
目前nas已发布了python sdk，并在17天前发布了3.1.0版本SDK，如果没能解决您的需求，建议您通过工单进行反馈，可以得到更快的响应:D
