### ISSUE TITLE
readme里的Regions and zones. 链接404了

### ISSUE THREAD

**Issue by DeoLeung** [aliyun/aliyun-openapi-python-sdk#218]
RT
----
https://www.alibabacloud.com/help/zh/doc-detail/40654.htm

**Comment by Qingtang-SDK** [comment]
您好，感谢您的反馈，我们马上修正这个问题。谢谢！
Region & Zones （地域和可用区）的文档正确链接是在这里：  https://help.aliyun.com/document_detail/40654.html

**Comment by wallisyan** [comment]
您好？我们已在Python SDK Core最新的的版本，修正了这个问题。
此问题将关闭
