### ISSUE TITLE
【容器服务】 POST相关接口完全无法使用

### ISSUE THREAD

**Issue by jokimina** [aliyun/aliyun-openapi-python-sdk#219]
* **Python Version**: 3.7.1
* **aliyunsdkcore Version**: aliyun-python-sdk-core==2.12.0
--

* **API**:
https://github.com/aliyun/aliyun-openapi-python-sdk/blob/master/aliyun-python-sdk-cs/aliyunsdkcs/request/v20151215/CreateClusterRequest.py

 

https://github.com/aliyun/aliyun-openapi-python-sdk/blob/master/aliyun-python-sdk-core/aliyunsdkcore/client.py#L229-L233
https://github.com/aliyun/aliyun-openapi-python-sdk/blob/master/aliyun-python-sdk-core/aliyunsdkcore/client.py#L263-L265

https://help.aliyun.com/document_detail/26054.html?spm=a2c4g.11174283.6.759.1b5f7a22JLbhKF
需要json格式的POST请求
大哥们, 你们SDK写完有自己调用过么,  写死了直接就urlencode,  怎么跑的通好么...

----------- 
![image](https://user-images.githubusercontent.com/11460661/54099434-4928c280-43f4-11e9-85a0-a64abc418213.png)

我自己的场景, 改成这样勉强跑通了, 不知有没有更优方式, 不想单独去维护一个分支...

---- 
![image](https://user-images.githubusercontent.com/11460661/54099479-80976f00-43f4-11e9-901b-968c5c563b2a.png)

这个参数也是很无语,  一下布尔一下string是闹哪样.......

**Comment by Qingtang-SDK** [comment]
您好，这个问题我们已经收到，感谢您的反馈，我们将尽快解决这个问题，有任何进展会及时通知您。给您造成的不便，我们深感抱歉，谢谢！

**Comment by jokimina** [comment]
目前暂时先通过monkey patch的方式替换了_make_http_response 正常用着了..

**Comment by 824750130** [comment]
您是否还有问题？如果没反馈我们将在3天内关闭，如有疑问请重新打开。
