### ISSUE TITLE
aliyun_python_sdk_core_v3 requests get exception of "TypeError: the JSON object must be str, not 'bytes'"

### ISSUE THREAD

**Issue by qhgongzi** [aliyun/aliyun-openapi-python-sdk#22]
File "/xxxxx/py/lib/python3.5/site-packages/aliyunsdkcore/client.py", line 253, in do_action_with_exception
    body_obj = json.loads(body)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

the json.loads expect a string type, but in the sdk the body was a bytes  from http_response.read()

if change to 
`body_obj = json.loads(body.decode("utf-8"))` will works fine

**Comment by Ricky-Leo** [comment]
+1
有没有人修复一下？

**Comment by liuyangc3** [comment]
also client.py line 230

change
```
body_obj = json.loads(response_body)
to
```
body_obj = json.loads(response_body.decode("utf-8"))
```

**Comment by gaort** [comment]
@qhgongzi @Ricky-Leo @liuyangc3 
thanks for your feedback, this bug has been fixed in 2.5.0。
we're very grateful for your supports, hats off to you and thanks again.
