### ISSUE TITLE
吐嘈这个代码传参方式

### ISSUE THREAD

**Issue by ramwin** [aliyun/aliyun-openapi-python-sdk#222]
接口写成 [示例](https://api.aliyun.com/new?#/?product=Dysmsapi&api=SendSms&params={%22RegionId%22:%22default%22,%22PhoneNumbers%22:%2218812345678%22,%22SignName%22:%22%E5%85%AC%E5%8F%B8%E7%AD%BE%E5%90%8D%22,%22TemplateCode%22:%22SMS_153055065%22,%22TemplateParam%22:%22%22}&tab=DEMO&lang=PYTHON) 这样, 阿里的开发们你们不觉得难受吗? 几个参数的传入方式竟然需要是一行一行的代码去调用 ??? 学学[requests](http://docs.python-requests.org/zh_CN/latest/)的参数调用方式, 传个params或者data进去好吗?  

说真的用这个sdk不如直接自己手写requests请求来的简洁.

**Comment by Qingtang-SDK** [comment]
您好，感谢您的反馈。Python SDK不符合Python的规范，我们正在努力解决这个问题。目前，我们已经在开发Python SDK-V2，目的就是提供一个更简洁、更符合Python规范的SDK。

https://github.com/aliyun/alibabacloud-python-sdk-v2  

目前支持ECS的若干资源的管理。欢迎您试用，并提出您的宝贵意见。

**Comment by ramwin** [comment]
哦哦,好的.谢谢回复. 期待新版本的尽早上线.

**Comment by ramwin** [comment]
> 您好，感谢您的反馈。Python SDK不符合Python的规范，我们正在努力解决这个问题。目前，我们已经在开发Python SDK-V2，目的就是提供一个更简洁、更符合Python规范的SDK。
> 
> https://github.com/aliyun/alibabacloud-python-sdk-v2
> 
> 目前支持ECS的若干资源的管理。欢迎您试用，并提出您的宝贵意见。

你们的SDK-V2已经没更新了. 不知道你有没有被输送到社会. 马后炮: 我就知道早晚有一天你们会出运维事故的
