### ISSUE TITLE
Live streaming api does not has `DescribeLiveDomainLog` 

### ISSUE THREAD

**Issue by orangle** [aliyun/aliyun-openapi-python-sdk#224]
* **Python Version**:  python2.7.12
* **aliyunsdkcore Version**:  aliyun_python_sdk_live 3.7.3
* **API**: DescribeLiveDomainLog

Live streaming api does not has `DescribeLiveDomainLog`

**Comment by Qingtang-SDK** [comment]
Hi, @orangle ， thanks for your feedback, we will look into this problem and fix it as soon as possible. We apologize for your inconvenience. Thank you, have a nice day!

**Comment by wallisyan** [comment]
hi， After we had communication with Live team,  this api  is a private and should not be released.
