### ISSUE TITLE
python sdk缺少dts

### ISSUE THREAD

**Issue by duguwo** [aliyun/aliyun-openapi-python-sdk#225]
阿里云数据传输服务（DTS）在git的python sdk中没有，官网上文档又少，使用起来很不方便

**Comment by wallisyan** [comment]
您好，这个问题我们已经收到，感谢您的反馈，我们将尽快解决这个问题，有任何进展会及时通知您。给您造成的不便，我们深感抱歉，谢谢！

**Comment by wallisyan** [comment]
您好？aliyun-python-sdk-dts 已经发布，您可以通过 `pip install aliyun-python-sdk-dts` 进行安装。
此问题将关闭
