### ISSUE TITLE
aliyun-python-sdk-imagesearch could not work with python3

### ISSUE THREAD

**Issue by kn45** [aliyun/aliyun-openapi-python-sdk#226]
* **Python Version**: 3.6.6
* **aliyunsdkcore Version**: 2.13.3
* **API**: aliyun-python-sdk-imagesearch

 
aliyun-python-sdk-imagesearch could not work with python3 due to the string encoding difference between py2 and py3. (It could not pass the simplest testing script). I hacked the code for temporal use however kindly update this sdk since it's a paid service. Thank you!

**Comment by Qingtang-SDK** [comment]
Hi, @kn45 ,  thanks for your feedback and we apologize for the inconvenience. We will look into this issue and fix it as soon as possible. Again, thank you.

**Comment by 824750130** [comment]
Do you still have questions? If there is no feedback, we will close the issue within 3 days. If you have any questions, please reopen it.
