### ISSUE TITLE
aliyunsdkcdn 的依赖配置有问题

### ISSUE THREAD

**Issue by songww** [aliyun/aliyun-openapi-python-sdk#23]
aliyunsdkcdn 依赖 `aliyun-python-sdk-core`，但兼容py3的包名为`aliyun-python-sdk-core-v3`。导致其无法通过pip3安装.
setup.py内可以判断下当前python版本动态变更依赖

**Comment by ImKcat** [comment]
Same as `aliyun-python-sdk-sts`

**Comment by gaort** [comment]
@songww @ImKcat 您好，相关的问题已经在9月27日修复，并已同步到pypi，建议您重试一下 😄
