### ISSUE TITLE
获取解析列表QueryDSRecordRequest接口报域名不存在

### ISSUE THREAD

**Issue by busyboy-ws** [aliyun/aliyun-openapi-python-sdk#230]
* **Python Version**: 3.6
* **aliyunsdkcore Version**: aliyun-python-sdk-domain==3.12.1
* **API**:  接口名：QueryDSRecordRequest

 
使用该sdk的QueryDSRecordRequest接口时报错。错误如下：
```
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 400 Error:DomainNotExist The domain name does not exist
```

**Comment by wallisyan** [comment]
您好，这个问题我们已经收到，感谢您的反馈，我们将尽快解决这个问题，有任何进展会及时通知您。给您造成的不便，我们深感抱歉，谢谢！

**Comment by wallisyan** [comment]
您好，SDK只是忠实反应服务端的响应，建议您检查相关传入参数。
此问题将关闭
