### ISSUE TITLE
the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by jasonhu5** [aliyun/aliyun-openapi-python-sdk#244]
使用`aliyunsdkgreen.request.extension`的`ClientUploader`上传文件时，`uploadFile()` 和 `uploadBytes()` 会报错（见标题），以下是报错的位置

https://github.com/aliyun/aliyun-openapi-python-sdk/blob/eac3836af64828428a057dc9af6c195d77e4565f/aliyun-python-sdk-green/aliyunsdkgreen/request/extension/ClientUploader.py#L45

暂时是如下修改了改源文件才能正常运行
```python
        # start fix
        try:
            response = response.decode("utf-8")
        except:
            pass
        # end fix
        result = json.loads(response)
```

**Comment by wallisyan** [comment]
您好，这个问题我们已经收到，感谢您的反馈，我们将积极和产品方沟通，尽快解决这个问题，有任何进展会及时通知您。给您造成的不便，我们深感抱歉，谢谢！

**Comment by 824750130** [comment]
您是否还有问题？如果没反馈我们将在3天内关闭，如有疑问请重新打开。
