### ISSUE TITLE
aliyun-python-sdk-iot 更新能不能不要这么随意

### ISSUE THREAD

**Issue by rsonghuster** [aliyun/aliyun-openapi-python-sdk#245]
aliyun-python-sdk-iot 这个更新能不能稍微有点节操， 都7.xx了， 动不动就是breaking change的大版本。。。。。

**Comment by wallisyan** [comment]
您好，这个问题我们已经收到，感谢您的反馈，我们将积极和产品方沟通，尽快解决这个问题，有任何进展会及时通知您。给您造成的不便，我们深感抱歉，谢谢！

**Comment by rsonghuster** [comment]
https://github.com/aliyun/aliyun-openapi-python-sdk/tree/master/aliyun-python-sdk-cdn/aliyunsdkcdn/request

能不能参考 cdn 的做法， 更换了api 版本，但是新版本的sdk 是兼容老的 sdk的， iot 的python sdk 能不能发布一个新的sdk， 兼容 6.xx 的版本。 我们这边是内置iot的sdk 做一些服务，如果iot那边不能保持向下兼容，我们这边很难做， 因为有的用户已经使用了我们内置的 6.xx 版本， 我们一旦升级就会影响用户

**Comment by wallisyan** [comment]
您好，您的建议已提交至IOT团队，此问题将关闭
