### ISSUE TITLE
billing API不支持查询某一天的数据

### ISSUE THREAD

**Issue by jasminewu229** [aliyun/aliyun-openapi-python-sdk#259]
* **Python Version**:  Python 3.6.4
* **aliyunsdkcore Version**:
aliyun-python-sdk-bssopenapi 1.2.2                     <pip>
aliyun-python-sdk-core    2.13.4                    <pip>
aliyun-python-sdk-core-v3 2.11.0                    <pip>
* **API**:  QueryBillRequest

 
Billing API 的billing cycle只能是月份，不能是日期，不能查询某一天的消费情况

**Comment by wallisyan** [comment]
您好，产品API问题，您可以参照文档：https://help.aliyun.com/document_detail/100392.html。如果没能解决您的需求，建议您通过工单进行反馈，可以得到更快的响应。谢谢

**Comment by wallisyan** [comment]
此问题将关闭
