### ISSUE TITLE
CDN的SDK缺失模块DescribeDomainRealTimeTrafficData

### ISSUE THREAD

**Issue by xiongxianzhu** [aliyun/aliyun-openapi-python-sdk#261]
* **Python Version**: python==3.6.8
* **aliyunsdkcore Version**:  aliyun-python-sdk-core-v3==2.13.3
* **API**: aliyun-python-sdk-cdn==3.0.8

CDN文档存在接口`DescribeDomainRealTimeTrafficData`, 但CDN SDK缺失相应的模块。

`DescribeDomainRealTimeTrafficData`的文档：https://help.aliyun.com/document_detail/91146.html?spm=a2c4g.11186623.6.663.7b793ab5ZLjwYt

缺失模块`aliyunsdkcdn.request.v20180510.DescribeDomainRealTimeTrafficData `

**Comment by wallisyan** [comment]
您好，和产品方沟通之后，确实是SDK当中接口缺失，已经将该问题反馈给产品方，他们将尽快重新生成并发布新版本。谢谢您的反馈

**Comment by xiongxianzhu** [comment]
好的， 谢谢~
