### ISSUE TITLE
scdn-sdk没有BatchSetScdnDomainConfigs方法

### ISSUE THREAD

**Issue by xushiba** [aliyun/aliyun-openapi-python-sdk#263]
![image](https://user-images.githubusercontent.com/42633258/57771202-a4549980-7744-11e9-8091-f2858eb94a42.png)
浏览器查看到更改scdn域名配置信息的BatchSetScdnDomainConfigs方法，在python-sdk里面没有找到，对用的php-sdk就有这个方法

**Comment by wallisyan** [comment]
您的问题已收到，我们会尽快和产品团队沟通发布新的SCDN Python版本，感谢您的反馈。

**Comment by wallisyan** [comment]
您好，SCDN产品已经发布1.2.4版本，该版本包含BatchSetScdnDomainConfigs接口，您可以通过`pip install aliyun-python-sdk-scdn --upgrade` 升级您的scdn版本库。感谢您的反馈。
此问题将关闭
