### ISSUE TITLE
When is Python 3 going to be supported?

### ISSUE THREAD

**Issue by jbasko** [aliyun/aliyun-openapi-python-sdk#264]
Is this actively maintained and is there any work going on to make it work with Python 3? I am trying to manage an ECS instance with ansible and the installation fails because this package requires < Python 3 which means I can't even install this.

**Comment by mpluhar** [comment]
Same here

**Comment by 824750130** [comment]
Do you still have questions? If there is no feedback, we will close the issue within 3 days. If you have any questions, please reopen it.
