### ISSUE TITLE
api功能优化

### ISSUE THREAD

**Issue by laopang2018** [aliyun/aliyun-openapi-python-sdk#265]
* **Python Version**:
3.7
* **aliyunsdkcore Version**:
4.16.9
* **API**:
StartInstanceRequest
 
from aliyunsdkecs.request.v20140526.StartInstanceRequest import StartInstanceRequest
from aliyunsdkecs.request.v20140526.StopInstanceRequest import StopInstanceRequest
from aliyunsdkecs.request.v20140526.RebootInstanceRequest import RebootInstanceRequest
from aliyunsdkecs.request.v20140526.DeleteInstanceRequest import DeleteInstanceRequest
from aliyunsdkecs.request.v20140526.RenewInstanceRequest import RenewInstanceRequest
from aliyunsdkecs.request.v20140526.DescribeSecurityGroupsRequest import DescribeSecurityGroupsRequest
from aliyunsdkecs.request.v20140526.JoinSecurityGroupRequest import JoinSecurityGroupRequest
from aliyunsdkecs.request.v20140526.LeaveSecurityGroupRequest import LeaveSecurityGroupRequest
from aliyunsdkecs.request.v20140526.DescribeInstanceTypeFamiliesRequest import DescribeInstanceTypeFamiliesRequest
阿里云这 sdk只能一个一个导，很麻烦，要导很多文件，

from aliyunsdkecs.request import v20140526 as ecs

ecs.StartInstanceRequest.StartInstanceRequest(）
不能像我这样使用，能否更新一下代码！

**Comment by 824750130** [comment]
您是否还有问题？如果没反馈我们将在3天内关闭，如有疑问请重新打开。
