### ISSUE TITLE
aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.HttpError HTTPConnectionPool

### ISSUE THREAD

**Issue by xrzheny** [aliyun/aliyun-openapi-python-sdk#266]
aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.HttpError HTTPConnectionPool(host='green.cn-hangzhou.aliyuncs.com', port=80): Max retries exceeded with url: /green/image/scan?RegionId=cn-hangzhou (Caused by ConnectTimeoutError(<aliyunsdkcore.vendored.requests.packages.urllib3.connection.HTTPConnection object at 0x00000165196DCC88>, 'Connection to green.cn-hangzhou.aliyuncs.com timed out. (connect timeout=5)'))
使用阿里内容安全审核的时候，采用本地上传二进制字节流的方式上传图片，大概能跑几十张就会报这个错

**Comment by wallisyan** [comment]
您好，您的问题已收到，请问您具体调用的是哪个API？

**Comment by xrzheny** [comment]
https://promotion.aliyun.com/ntms/act/lvwangdemo.html?spm=5176.55804.911092.btn3.77ca8aee410RJ3，内容安全图片审核API

**Comment by 824750130** [comment]
您是否还有问题？如果没反馈我们将在3天内关闭，如有疑问请重新打开。

**Comment by Yuyang105** [comment]
咋就关了，啥原因
