### ISSUE TITLE
aliyun-python-sdk-eci CreateContainerGroupRequest missing some parameters

### ISSUE THREAD

**Issue by iamzhangdapao** [aliyun/aliyun-openapi-python-sdk#267]
* **Python Version**: 3.7.3
* **aliyunsdkcore Version**: 2.13.4
* **API**: aliyun-python-sdk-eci 

 
- aliyun-python-sdk-eci version: 1.0.4

In ECI official API docs, `CreateContainerGroup` section, have two parameters: `Cpu` and `Memory`, but there are no corresponding methods for these parameters in SDK `aliyunsdkeci.request.v20180808.CreateContainerGroupRequest.CreateContainerGroupRequest`  

so is docs error or SDK missing corresponding method?

docs link: `https://help.aliyun.com/document_detail/90341.html?spm=a2c4g.11186623.6.628.4b5141b9eWYQfd`
docs last update: `2019-06-06 15:12:39`

**Comment by 824750130** [comment]
Do you still have questions? If there is no feedback, we will close the issue within 3 days. If you have any questions, please reopen it.
