### ISSUE TITLE
git 上 sdk-alidns 与 pip 仓库代码不一致

### ISSUE THREAD

**Issue by Jatai0209** [aliyun/aliyun-openapi-python-sdk#269]
批量更新domain record 接口， git 上的操作是OperateBatchDomainRequest 而 pip (aliyun-python-sdk-alidns == 2.0.7)仓库上是UpdateBatchDomainRecordsRequest, 且你们的官方文档上面的操作是以OperateBatchDomainRequest

**Comment by wallisyan** [comment]
您好，问题已收到，我们和产品方沟通下，确认下是文档还是接口的问题。
稍后给您反馈
感谢

**Comment by wallisyan** [comment]
亲，您好，目前批量更新接口以官方文档OperateBatchDomainRequest为准。因为某些原因，该产品暂不在pypi更新。您可以参照官方文档组装api或者使用源码方式（python setup.py install）安装git上的alidns产品。

**Comment by Jatai0209** [comment]
打扰一下， 还有一个问题， OperateBatchDomainRequest 这个接口操作类型只接受 add 与 del 类型（文档上面的参数是这样）吗？但在可试化调试上面的参数却有 NewRR, NewType, NewValue, 请问一下， 该接口是否支持对解析记录的批量更新？

**Comment by wallisyan** [comment]
您好， OperateBatchDomainRequest 一切操作以官方文档为准。
1， OperateBatchDomainRequest不支持批量更新
2， NewRR, NewType, NewValue等参数已和产品方沟通，是不可用参数。
建议一切以官方文档为准
感谢
