### ISSUE TITLE
[Errno 10060] 

### ISSUE THREAD

**Issue by yxy-he** [aliyun/aliyun-openapi-python-sdk#28]
经常会出现以下报错，并不是每次都有，但是今天非常频繁
```
aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.ServerUnreachable Unable to connect server: [Errno 10060]
```

**Comment by gaort** [comment]
@yxy-he 
感谢您的反馈，十分抱歉这么久才回复您
这种情况大多是由于网络原因导致的
如果您的场景包含跨域请求场景(比如从北京服务器发起到德国服务器的调用)，这种情况会相对较多
您可以通过对比 自己服务器所在的region，和您初始化client时传入的region 来确认上述问题

**Comment by fanlifei** [comment]
SDK.ServerUnreachable Unable to connect server: [Errno -2] Name or service not known
rds
