### ISSUE TITLE
aliyunsdkcas无法CreateUserCertificate,和最新文档以及OPEN API EXPLORER不一致

### ISSUE THREAD

**Issue by Shandawei** [aliyun/aliyun-openapi-python-sdk#280]
* **Python Version**:3.7
* **aliyunsdkcore Version**:2.13.5
* **API**:aliyunsdkcas.request.v20180813

 
1.该版本接口缺少`CreateUserCertificate`,和最新文档以及`OPEN API EXPLORER`不一致
2.`aliyunsdkcore`中不存在`cas`服务.

**Comment by wallisyan** [comment]
您好, 产品问题请发工单解决.
此问题将关闭
