### ISSUE TITLE
aliyun-python-sdk-core-v3中有个代码我很想吐槽下

### ISSUE THREAD

**Issue by yukk670** [aliyun/aliyun-openapi-python-sdk#285]
class CommonRequest(AcsRequest):
        super(CommonRequest, self).__init__(product)
        self._method = "GET"

class AcsRequest:
       def __init__(self, product, version=None,
                 action_name=None,
                 location_service_code=None,
                 location_endpoint_type='openAPI',
                 accept_format=None,
                 protocol_type=None,
                 method=None):
                 self._method = method
好了，假如我给product赋值{'method':'POST'}，很明显这个method赋值又被后面的GET覆盖了，等于白搭

**Comment by wallisyan** [comment]
您好, 您可以详细看下CommonRequest的使用方式.
CommonRequest 初始化是不传递method的, 您可以通过以下代码所示方式设置method
```python
request = CommonRequest()
request.set_method("POST")
```

**Comment by yukk670** [comment]
额，我知道可以直接用set，我的意思是这个类的逻辑好像有一点问题，既然提供了product的为父方法的赋值，后续又手动更改父方法的值
