### ISSUE TITLE
是否设置 request.set_Region价格不同

### ISSUE THREAD

**Issue by toywei** [aliyun/aliyun-openapi-python-sdk#286]
# Version
Python Version:py3.7
aliyunsdkcore Version:v20171214
API:aliyunsdkbssopenapi/request/v20171214/ GetSubscriptionPriceRequest GetPayAsYouGoPriceRequest 
Type:ecs-NewOrder

# code
https://github.com/aliyun/aliyun-openapi-python-sdk/blob/master/aliyun-python-sdk-bssopenapi/aliyunsdkbssopenapi/endpoint.py

# path
Lib/site-packages/aliyunsdkbssopenapi/request/v20171214/GetSubscriptionPriceRequest.py

Lib/site-packages/aliyunsdkbssopenapi/request/v20171214/GetPayAsYouGoPriceRequest.py

# 是否设置 request.set_Region价格不同

### 设置
from aliyunsdkcore.client import AcsClient
from aliyunsdkbssopenapi.request.v20171214.GetSubscriptionPriceRequest import GetSubscriptionPriceRequest
from mytest.mytestKey import myak, mysecret

client = AcsClient(myak, mysecret, 'cn-qingdao')

request = GetSubscriptionPriceRequest()
request.set_accept_format('json')

request.set_SubscriptionType("Subscription")
request.set_ProductCode("ecs")
request.set_OrderType("NewOrder")
request.set_ModuleLists([{
    "ModuleCode": "InstanceType",
    "Config": "InstanceType:ecs.c5.xlarge"
}, {
    "ModuleCode": "SystemDisk",
    "Config": "SystemDisk.Category:cloud_efficiency,SystemDisk.Size:40"
}, {
    "ModuleCode": "DataDisk",
    "Config": "DataDisk.Category:cloud_efficiency,DataDisk.Size:40"
}, {
    "ModuleCode": "InternetMaxBandwidthOut",
    "Config": "InternetMaxBandwidthOut:1024,InternetMaxBandwidthOut.IsFlowType:5"
}
])
request.set_ServicePeriodUnit("Month")
request.set_ServicePeriodQuantity(1)
request.set_Region("cn-qingdao")
request.set_Quantity(1)

response = client.do_action_with_exception(request)
print(str(response, encoding='utf-8'))

{"Data":{"Quantity":1,"DiscountPrice":0.0,"ModuleDetails":{"ModuleDetail":[{"ModuleCode":"InstanceType","UnitPrice":0.0,"CostAfterDiscount":358.0,"OriginalCost":358.0,"InvoiceDiscount":0.0},{"ModuleCode":"SystemDisk","UnitPrice":0.0,"CostAfterDiscount":14.0,"OriginalCost":14.0,"InvoiceDiscount":0.0},{"ModuleCode":"DataDisk","UnitPrice":0.0,"CostAfterDiscount":14.0,"OriginalCost":14.0,"InvoiceDiscount":0.0},{"ModuleCode":"InternetMaxBandwidthOut","UnitPrice":0.0,"CostAfterDiscount":20.7,"OriginalCost":20.7,"InvoiceDiscount":0.0}]},"PromotionDetails":{"PromotionDetail":[]},"OriginalPrice":406.7,"TradePrice":406.7,"Currency":"CNY"},"Message":"Successful!","RequestId":"234FD92C-A747-4E46-BF46-800ABEB7B4A6","Success":true,"Code":"Success"}`

### 不设置

from aliyunsdkcore.client import AcsClient
from aliyunsdkbssopenapi.request.v20171214.GetSubscriptionPriceRequest import GetSubscriptionPriceRequest
from mytest.mytestKey import myak, mysecret

client = AcsClient(myak, mysecret, 'cn-qingdao')

request = GetSubscriptionPriceRequest()
request.set_accept_format('json')

request.set_SubscriptionType("Subscription")
request.set_ProductCode("ecs")
request.set_OrderType("NewOrder")
request.set_ModuleLists([{
    "ModuleCode": "InstanceType",
    "Config": "InstanceType:ecs.c5.xlarge"
}, {
    "ModuleCode": "SystemDisk",
    "Config": "SystemDisk.Category:cloud_efficiency,SystemDisk.Size:40"
}, {
    "ModuleCode": "DataDisk",
    "Config": "DataDisk.Category:cloud_efficiency,DataDisk.Size:40"
}, {
    "ModuleCode": "InternetMaxBandwidthOut",
    "Config": "InternetMaxBandwidthOut:1024,InternetMaxBandwidthOut.IsFlowType:5"
}
])
request.set_ServicePeriodUnit("Month")
request.set_ServicePeriodQuantity(1)

request.set_Quantity(1)

response = client.do_action_with_exception(request)
print(str(response, encoding='utf-8'))

{"Data":{"Quantity":1,"DiscountPrice":0.0,"ModuleDetails":{"ModuleDetail":[{"ModuleCode":"InstanceType","UnitPrice":0.0,"CostAfterDiscount":358.0,"OriginalCost":358.0,"InvoiceDiscount":0.0},{"ModuleCode":"SystemDisk","UnitPrice":0.0,"CostAfterDiscount":14.0,"OriginalCost":14.0,"InvoiceDiscount":0.0},{"ModuleCode":"DataDisk","UnitPrice":0.0,"CostAfterDiscount":14.0,"OriginalCost":14.0,"InvoiceDiscount":0.0},{"ModuleCode":"InternetMaxBandwidthOut","UnitPrice":0.0,"CostAfterDiscount":23.0,"OriginalCost":23.0,"InvoiceDiscount":0.0}]},"PromotionDetails":{"PromotionDetail":[]},"OriginalPrice":409.0,"TradePrice":409.0,"Currency":"CNY"},"Message":"Successful!","RequestId":"3E780F52-D84A-4E96-B404-9BE5AD313BB6","Success":true,"Code":"Success"}

# 问题：
client = AcsClient(myak, mysecret, 'cn-qingdao')已经可以实现endpoint的寻址逻辑
（https://help.aliyun.com/document_detail/92074.html Endpoint管理更新时间：2019-01-23 01:49:56）
https://github.com/aliyun/aliyun-openapi-python-sdk/blob/master/aliyun-python-sdk-bssopenapi/aliyunsdkbssopenapi/endpoint.py
是否冗余的、不必openapi-sdk中暴露？
且更不应该强制调用时重复配置？

**Comment by wallisyan** [comment]
您好, 
1, 关于RegionId是否与价格有关.
您设置的RegionId是cn-qingdao; 您不设置, sdk 默认是cn-hangzhou. 二者解析到的endpoint不同, 可能存在价格差异, 具体需要参照产品方的设定.
2, 关于bssopenapi 下的endpoint.py 是否存在代码冗余.
endpoint的解析是在client.do_action_with_exception(request) 部分, 内部会调用bssopenapi 下的endpoint.py文件. 参照https://github.com/aliyun/aliyun-openapi-python-sdk/blob/master/aliyun-python-sdk-core/aliyunsdkcore/endpoint/default_endpoint_resolver.py
