### ISSUE TITLE
找不到HttpContentHelper

### ISSUE THREAD

**Issue by fzlee** [aliyun/aliyun-openapi-python-sdk#290]
* **Python Version**:
3.7

* **aliyunsdkcore Version**:
aliyun-python-sdk-core-v3==2.13.10
aliyun-python-sdk-green==3.5.1

* **API**:
图片内容鉴定

按照[官方的例子](https://help.aliyun.com/document_detail/53432.html?spm=a2c4g.11186623.6.744.760d66adblRmbw)
```python
from aliyunsdkcore import client
from aliyunsdkgreen.request.v20180509 import ImageSyncScanRequest
from aliyunsdkgreen.request.extension import HttpContentHelper
import json
import uuid
```
不能导入HttpContentHelper,  查看安装包， 压根没有extension文件

**Comment by wallisyan** [comment]
您好, 官方例子所示demo的extension 文件在aliyun-python-sdk-green==3.5.0版本依然保留, 您可以先指定该版本使用. 我们会尽快和该团队协商更新文档.

**Comment by fzlee** [comment]
好的， 谢谢

**Comment by fanslin** [comment]
大坑啊 ，搞了大半天都安装不上。晕死

**Comment by lufeisan** [comment]
今天还没弄好

**Comment by KobeBeyond** [comment]
+1 今天还没弄好

**Comment by atois** [comment]
mark
2024年2月26日

**Comment by atois** [comment]
已经2024年了root@iZt4nb1h6ve8ki2wg6igjzZ:~# python3 ocr.py 
Traceback (most recent call last):
  File "/root/ocr.py", line 5, in <module>
    from aliyunsdkgreen.request.extension import HttpContentHelper
ModuleNotFoundError: No module named 'aliyunsdkgreen.request.extension'
