### ISSUE TITLE
PreTaxAmount is not returned by aliyunsdkbssopenapi.request.v20171214.QueryInstanceBillRequest

### ISSUE THREAD

**Issue by mirochnik** [aliyun/aliyun-openapi-python-sdk#291]
* **Python Version**: 3.6.2
* **aliyunsdkcore Version**: 2.13.10
* **API**: aliyunsdkbssopenapi.request.v20171214.QueryInstanceBillRequest

 
A week ago on 24 Oct 2019, the API was returning PreTaxAmount in the list of fields. It is not returned today anymore. It should be there according to the documentation https://www.alibabacloud.com/help/doc-detail/100400.htm?spm=a2c63.p38356.b99.41.641a62b6hPYHJp

**Comment by 824750130** [comment]
Do you still have questions? If there is no feedback, we will close the issue within 3 days. If you have any questions, please reopen it.
