### ISSUE TITLE
sts 上传video

### ISSUE THREAD

**Issue by inshyma** [aliyun/aliyun-openapi-python-sdk#292]
* **Python Version**:
* **aliyunsdkcore Version**:
* **API**:

**Comment by inshyma** [comment]
怎么上传accessKeyId是STS.开头的video 否则报错:Type: ServerException, Code: MissingSecurityToken, Message: SecurityToken is mandatory for this action., HTTPStatus: 400

**Comment by Qingtang-SDK** [comment]
> 怎么上传accessKeyId是STS.开头的video 否则报错:Type: ServerException, Code: MissingSecurityToken, Message: SecurityToken is mandatory for this action., HTTPStatus: 400

请问您调用的样例代码是怎样的？

**Comment by 824750130** [comment]
您是否还有问题？如果没反馈我们将在3天内关闭，如有疑问请重新打开。
