### ISSUE TITLE
阿里云kubernetes版容器中关于应用的api没有吗？如果有的话，请告知。如果没有，可否告知大概啥时候出这个api

### ISSUE THREAD

**Issue by feixiaohuijava** [aliyun/aliyun-openapi-python-sdk#293]
* **Python Version**:
* **aliyunsdkcore Version**:
* **API**:

**Comment by 824750130** [comment]
在新版本4.8.0中已经支持应用相关的api，请下载新版本aliyun-python-sdk-cs。
