### ISSUE TITLE
'UpdateTrailRequest' object has no attribute 'set_EventRW'"

### ISSUE THREAD

**Issue by jasminewu229** [aliyun/aliyun-openapi-python-sdk#294]
* **Python Version**: Python 3.7.4
* **aliyunsdkcore Version**: aliyun-python-sdk-actiontrail==2.0.0
* **API**: UpdateTrailRequest

 
I've done 'pip install aliyun-python-sdk-actiontrail' according to https://develop.aliyun.com/tools/sdk?#/python

And it installed version 2.0.0 SDK for me, and it doesn't seem to have included set_EventRW in UpdateTrailRequest.py

What's going on?

**Comment by 824750130** [comment]
This issue has been fixed in version 2.0.1,
