### ISSUE TITLE
请问下 aliyun-python-sdk-core-v3 和 aliyun-python-sdk-core 有什么区别？

### ISSUE THREAD

**Issue by rsonghuster** [aliyun/aliyun-openapi-python-sdk#298]
请问下 aliyun-python-sdk-core-v3 和 aliyun-python-sdk-core 有什么区别？

https://pypi.org/project/aliyun-python-sdk-core/

https://pypi.org/project/aliyun-python-sdk-core-v3/

**Comment by JacksonTian** [comment]
没区别了。之前的 Python 2 和 3 是分别实现的。后来经过重构后，2/3 都一套代码支持了。推荐用不带 v3 的。
