### ISSUE TITLE
demo please

### ISSUE THREAD

**Issue by yaiba** [aliyun/aliyun-openapi-python-sdk#3]
用sdk还一直 SignatureDoesNotMatch - -，给几个demo供参考一下吧

**Comment by liuyangc3** [comment]
@yaiba  https://github.com/nxintech/Charlie/blob/master/aliyun/sdk_sample.py
亲测可用

**Comment by gaort** [comment]
@yaiba @liuyangc3 
感谢您的反馈，十分抱歉这么久才回复您
您可以在阿里云官网找到python sdk的相关使用手册
https://help.aliyun.com/document_detail/53090.html?spm=5176.136436.698463.7.HIY33d
相关接口的调用示例，您可以通过APIExplorer来自动生成
https://api.aliyun.com
