### ISSUE TITLE
dts有没有python的使用文档

### ISSUE THREAD

**Issue by worsun** [aliyun/aliyun-openapi-python-sdk#307]
找了好久，没有发现dts的python版demo。官网只有java，如果想用python还需要看完源码吗？

* **Python Version**:
* **aliyunsdkcore Version**:
* **API**:

**Comment by 824750130** [comment]
在OpenAPI Explorer可以找到相应接口的demo https://api.aliyun.com/

**Comment by 824750130** [comment]
您是否还有问题？如果没反馈我们将在3天内关闭，如有疑问请重新打开。
