### ISSUE TITLE
py3 pyinstall 打包exe 执行报错bug

### ISSUE THREAD

**Issue by silenceGuo** [aliyun/aliyun-openapi-python-sdk#308]
* **Python Version**:3.7
* **aliyunsdkcore Version**: from aliyunsdkcdn.request.v20180510.RefreshObjectCachesRequest import RefreshObjectCachesRequest
* **API**:RefreshObjectCaches

在使用aly cdn 刷新接口 RefreshObjectCaches通过pyinstaller 打包exe 运行会报错""" 
![image](https://user-images.githubusercontent.com/28891624/71076813-4d72df00-21c1-11ea-8f3e-f8a9e002e288.png)
在文件路径 "site-packages\aliyunsdkcore\vendored\requests\packages\urllib3\connectionpool.py", line 28, in <module>

#from .packages.six.moves import queue 修改为import queue 后重新打包修复成功，
是否有更好的处理方式，

**Comment by silenceGuo** [comment]
![Catch(12-18-18-06-36)](https://user-images.githubusercontent.com/28891624/71076897-6d0a0780-21c1-11ea-8d60-e19f03044354.jpg)

**Comment by 824750130** [comment]
您是否还有问题？如果没反馈我们将在3天内关闭，如有疑问请重新打开。
