### ISSUE TITLE
在文档提到的“默认凭证提供链”在SDK里面并没有提供

### ISSUE THREAD

**Issue by leonmax** [aliyun/aliyun-openapi-python-sdk#354]
* **Python Version**: 3.7
* **aliyunsdkcore Version**:  2.13.16
* **API**: aliyun-python-sdk-core

 

在 docs/2-Client-CN.md#使用默认凭证提供链 中有提到default credentials provider chain，不知道何时会提供。该功能在alibabacloud-python-sdk-v2这个repo里有，但那个sdk好像已经废弃，问题多多。希望尽快能在官方的库里面提供。

**Comment by 824750130** [comment]
文档描述有错误，已经修复，给您造成不便请谅解，此问题将关闭，如果还有问题，请重新打开。
