### ISSUE TITLE
aliyun-python-sdk-core-v3 的 json 解析问题

### ISSUE THREAD

**Issue by lfzyx** [aliyun/aliyun-openapi-python-sdk#36]
` File "***/aliyunsdkcore/profile/location_service.py", line 143, in find_product_domain_from_location_service
    result = json.loads(body)`

 ` File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__)) `

`TypeError: the JSON object must be str, not 'bytes'`

当然我直接改 aliyunsdkcore/profile/location_service.py 这个文件加上 .decode() 也可以，但还是希望你们解决下

**Comment by gaort** [comment]
@lfzyx 非常感谢您的反馈！该BUG已修复，谢谢您对阿里云一如既往的支持！
