### ISSUE TITLE
aliyunsdkcore/endpoints.xml 缺失短信服务地址

### ISSUE THREAD

**Issue by John60676** [aliyun/aliyun-openapi-python-sdk#37]
由于endpoints.xml 中缺少短信服务的URL（dysmsapi.aliyuncs.com），导致短信服务不能正常调用

**Comment by John60676** [comment]
是否因为 endpoints.xml 38行中的 'DomainName' 有误？
`<Product><ProductName>Sms</ProductName><DomainName>sms.aliyuncs.com</DomainName></Product>`

**Comment by John60676** [comment]
两天了都没人来处理一下？

**Comment by John60676** [comment]
@ssddn 我只是好奇为啥提了好几天了都没人提交版本修复，而且我看了一下，这个问题很早前就有了。前几个月有个commit修复了，但是不知道为啥最近 Dysmsapi 这个节点又在endpoint 里面丢失了

**Comment by ssddn** [comment]
我在阿里云平台上提交工单了，他们答复说尽快解决，不知道什么时候能更新上去。

**Comment by John60676** [comment]
@ssddn 我提工单问他们，他们都不知道 aliyun-python-sdk-core-v3 这个依赖包的存在🤷‍♀️，不管了。我自己已经修复了个版本用。版本提交上去了，合不合并随他们吧。这个issue留着给后面的人翻看

**Comment by gaort** [comment]
@John60676 十分感谢您的建议，关于您提到的问题，短信服务在调用demo中包含一行添加endpoint的代码，具体在：
https://help.aliyun.com/document_detail/55359.html?spm=5176.8195934.507901.12.UvCFaW

另外，添加到endpoint也是可以解决这个问题的，十分感谢您的提交，我们会内部讨论后决定是否合并，再次感谢！

**Comment by nssprite** [comment]
使用最新版aliyunsdkcore 2.6.2，endpoint.xml缺少dysmsapi配置。
参考：https://steemit.com/btc/@seatre/python-api

**Comment by gaort** [comment]
@nssprite 您好，endpoint.xml已经不再维护了
关于短信sdk出现cannotResolveEndpoint的问题，我们已经向相关团队反馈
建议您提交工单，我们会尽快推进这个问题的解决

**Comment by jxyowen** [comment]
您好，resolve endpoint 类似于dns解析，sdk在发出请求前， 会先通过endpoint解析服务，取得对应 产品及地区  的endpoint。 如果云产品没有在解析服务上做配置，就会出现cannotResolveEndpoint。  您工单得到的解决方案是手动设定 endpoint，是否解决了问题？

**Comment by bunnyc1986** [comment]
工单上的解决方案是我自己看到这个Issue以及比较Demo以后得到的。
手动添加endpoint以后，已经可以正常使用。

**Comment by bunnyc1986** [comment]
为什么短信服务不愿意在解析服务上做配置呢？
