### ISSUE TITLE
aliyun-python-sdk-batchcompute and aliyun-python-sdk-bsn outdated on PyPi

### ISSUE THREAD

**Issue by glaubitz** [aliyun/aliyun-openapi-python-sdk#370]
Both aliyun-python-sdk-batchcompute and aliyun-python-sdk-bsn are outdated on PyPi and pull in the old aliyun-python-sdk-core-v3 dependency.

- https://pypi.org/project/aliyun-python-sdk-batchcompute/#history
- https://pypi.org/project/aliyun-python-sdk-bsn/#history

Could you please update both packages on PyPi?

Thanks!

**Comment by glaubitz** [comment]
Ping. Any news on this? Could these packages be updated on PyPi? The ones on PyPi still have the ```-core-v3``` package in their dependencies.

**Comment by glaubitz** [comment]
Another gentle ping.

**Comment by JacksonTian** [comment]
Hi @glaubitz , we confirmed with product part, the two packages don't update anymore.

**Comment by JacksonTian** [comment]
Are you use these packages in your project?

**Comment by glaubitz** [comment]
So, these two packages can be ignored completely? If yes, I will just drop them from packaging.

I was not sure whether they are still needed or not as they are still part of the SDK sources and there are newer versions in the SDK as compared to what is on PyPi.

**Comment by glaubitz** [comment]
If the two packages are deprecated, I suggest removing them from the git tree to avoid confusion. They can be restored from git history if that should be necessary in the future.

**Comment by IvanaXu** [comment]
I find the version is not match on PyPi, e.g aliyunsdkcore & oss2
So I install them by github
