### ISSUE TITLE
aliyunsdkvcs--'GetDeviceLiveUrlRequest' object has no attribute 'add_body_params'

### ISSUE THREAD

**Issue by cmdjzs** [aliyun/aliyun-openapi-python-sdk#377]
* **Python Version**: 3.5.2
* **aliyunsdkcore Version**: 1.0.3
* **API**: aliyunsdkvcs

 
test code is copied from https://help.aliyun.com/document_detail/165196.html?spm=a2c4g.11186623.2.19.378c1bf4A39npX#doc-api-Vcs-GetDeviceLiveUrl;and vcs package is downloaded from here and setup(where pypi can't find it).
all of this by you provided, I didn't change any letter,and report error.
Traceback (most recent call last):
  File "test_ali_api.py", line 14, in <module>
    request.set_CorpId("jyz")
  File "D:\jyz\vir_jyz\venv\lib\site-packages\aliyun_python_sdk_vcs-1.0.7-py3.5.egg\aliyunsdkvcs\request\v20200515\GetDeviceLiveUrlRequest.py", line 38, in set_CorpId
AttributeError: 'GetDeviceLiveUrlRequest' object has no attribute 'add_body_params'

**Comment by 824750130** [comment]
Upgrade your aliyun-python-sdk-core library please
