### ISSUE TITLE
UnicodeEncodeError raised with pytest cause of **sys.setdefaultencoding**

### ISSUE THREAD

**Issue by xuwei0455** [aliyun/aliyun-openapi-python-sdk#384]
* **Python Version**:
Python 2.7.16

* **aliyunsdkcore Version**:
2.13.23

 

I found some breaking change was import from 2.13.22, as follows:
``` python
diff --git a/aliyun-python-sdk-core/aliyunsdkcore/client.py b/aliyun-python-sdk-core/aliyunsdkcore/client.py
index 74567639..bd59f227 100644
--- a/aliyun-python-sdk-core/aliyunsdkcore/client.py
+++ b/aliyun-python-sdk-core/aliyunsdkcore/client.py
@@ -25,6 +25,7 @@ import logging
 import jmespath
 import copy
 import platform
+import sys

 import aliyunsdkcore
 from aliyunsdkcore.vendored.six.moves.urllib.parse import urlencode
@@ -55,6 +56,10 @@ from aliyunsdkcore.vendored.requests.structures import OrderedDict
 Acs default client module.
 """

+if sys.version_info.major == 2:
+    reload(sys)
+    sys.setdefaultencoding('utf-8')
+
 DEFAULT_READ_TIMEOUT = 10
 DEFAULT_CONNECTION_TIMEOUT = 5
```

This change may cause an effect with pytest, here has a base function in pytest/compat.py:
``` python
    def _escape_strings(val):
        """In py2 bytes and str are the same type, so return if it's a bytes
        object, return it unchanged if it is a full ascii string,
        otherwise escape it into its binary form.

        If it's a unicode string, change the unicode characters into
        unicode escapes.

        """
        if isinstance(val, bytes):
            try:
                return val.encode('ascii')
            except UnicodeEncodeError:
                return val.encode('string-escape')
        else:
            return val.encode('unicode-escape')
```

As the code above, if the value's type was a string, pytest try encode the value with **ASCII** encoding which was the default in python. but aliyun-openapi-python-sdk changes the default encoding to **UTF-8**, which will cause decode success and encode failed. so An UnicodeEncodeError will raise. 

First, as a base module, aliyun sdk should not import some breaking changes to users. And, I do not think **sys.setdefaultencoding** takes no effects, actually, the use of sys.setdefaultencoding() has always been discouraged.

**Comment by 824750130** [comment]
Thanks for your suggestion, the problem has been fixed in the 2.13.24 version.
