### ISSUE TITLE
使用python3.7调用sdk,提示签名不正确

### ISSUE THREAD

**Issue by cjloop** [aliyun/aliyun-openapi-python-sdk#390]
使用python3.7调用sdk,调用接口，报错，以下为调用代码：

from aliyunsdkcore import client
from aliyunsdkecs.request.v20140526.DescribeRegionsRequest import DescribeRegionsRequest

clientObj = client.AcsClient(decipher_by_aes(key_id), decipher_by_aes(key_secret))

request = DescribeRegionsRequest()
request.set_accept_format('json')
try:
    response_str = clientObj.do_action(request)
    
    return clientObj
except Exception as e: 
    
    return None

以下是报错信息：
"RequestId":"2E1AA9C3-5001-42F8-B81F-1295308F762F","Message":"The request signature does not conform to Aliyun standards. server string to sign is:POST&%2F&AccessKeyId%3DLTAIcTuxYzwLyjYC%26Action%3DDescribeRegions%26Format%3Djson%26RegionId%3Dcn-hangzhou%26SignatureMethod%3DHMAC-SHA1%26SignatureNonce%3D5e05add1-d6ae-5a34-b3e7-b32b917929ca%26SignatureType%3D%26SignatureVersion%3D1.0%26Timestamp%3D2020-08-03T07%253A50%253A04Z%26Version%3D2014-05-26","Recommend":"https://error-center.aliyun.com/status/search?Keyword=IncompleteSignature&source=PopGw","HostId":"ecs-cn-hangzhou.aliyuncs.com","Code":"IncompleteSignature"}

为什么会这样，不是sdk里面签名的吗？还会不完整？

**Comment by 824750130** [comment]
请问使用的aliyun-python-sdk-core版本是多少？ 以及确保ak是正确的。

**Comment by 18721585442** [comment]
版本是最新的2.13.25

**Comment by 18721585442** [comment]
https://pypi.org/project/aliyun-python-sdk-core/2.13.25/

**Comment by 18721585442** [comment]
ak信息肯定是正确的，我反复确认过，和官网查到的也是一样的。

**Comment by 824750130** [comment]
可以对比一下aliyunsdkcore/auth/composer/rpc_signature_composer.py 75行中string_to_sign与错误返回的string to sign是否一致，如果一致可以定位为ak问题。

**Comment by 18721585442** [comment]
sign_params {'Version': '2014-05-26', 'Action': 'DescribeRegions', 'Format': 'json', 'RegionId': 'cn-hangzhou', 'Timestamp': '2020-08-05T02:37:03Z', 'SignatureMethod': 'HMAC-SHA1', 'SignatureType': '', 'SignatureVersion': '1.0', 'SignatureNonce': '795caab8-e41a-57e4-b1fd-f36f1de53089', 'AccessKeyId': '7gohexx8BINKuDef'}
string_to_sign POST&%2F&AccessKeyId%3D7gohexx8BINKuDef%26Action%3DDescribeRegions%26Format%3Djson%26RegionId%3Dcn-hangzhou%26SignatureMethod%3DHMAC-SHA1%26SignatureNonce%3D795caab8-e41a-57e4-b1fd-f36f1de53089%26SignatureType%3D%26SignatureVersion%3D1.0%26Timestamp%3D2020-08-05T02%253A37%253A03Z%26Version%3D2014-05-26

**Comment by 18721585442** [comment]
返回的信息：
{'RequestId': '22348773-2046-43F9-81D6-0D6F20DD0BE2', 'Message': 'The request signature does not conform to Aliyun standards. server string to sign is:POST&%2F&AccessKeyId%3D7gohexx8BINKuDef%26Action%3DDescribeRegions%26Format%3Djson%26RegionId%3Dcn-hangzhou%26SignatureMethod%3DHMAC-SHA1%26SignatureNonce%3D795caab8-e41a-57e4-b1fd-f36f1de53089%26SignatureType%3D%26SignatureVersion%3D1.0%26Timestamp%3D2020-08-05T02%253A37%253A03Z%26Version%3D2014-05-26', 'Recommend': 'https://error-center.aliyun.com/status/search?Keyword=IncompleteSignature&source=PopGw', 'HostId': 'ecs-cn-hangzhou.aliyuncs.com', 'Code': 'IncompleteSignature'}

**Comment by 824750130** [comment]
两个字符串是相同的，请检查 Access Key ID 和 Access Key Secret 是否正确。

**Comment by 18721585442** [comment]
没有错啊，我在阿里云控制台查过了，也是这个，难道还要处理以下吗
![image](https://user-images.githubusercontent.com/47551949/89366937-72916f00-d70a-11ea-8a15-a095de138a61.png)

**Comment by 824750130** [comment]
decipher_by_aes方法获取ak是否有做什么处理？

**Comment by 18721585442** [comment]
这个方法，是因为ak信息存在我数据库中是加密的，这个是解密一下，你可以看下，rpc_signature_composer 中我打印的sign_params中的ak就是实际的ak，值和阿里云控制台上面的是一样的。

**Comment by 824750130** [comment]
是否是ak出现过变更数据库中没更新？

**Comment by 18721585442** [comment]
不是哦，传的值和数据库和阿里云控制台的信息都是一致的哦

**Comment by 824750130** [comment]
请加一下钉钉群号：11771185 帮助解决问题

**Comment by 18721585442** [comment]
无法找到该用户？

**Comment by 824750130** [comment]
搜索群组

**Comment by 18721585442** [comment]
搜不到，你拉我下，或者有结果，麻烦你告知一下，谢谢！！

**Comment by cjloop** [comment]
。。。。我使用自己另一个账号的ak信息，这个ak生成的时间比较近，发现sdk可以调用，难道你们对access key id有什么限制吗？
![image](https://user-images.githubusercontent.com/47551949/89376861-4504ef80-d723-11ea-813f-f00be65cc3c5.png)

**Comment by cjloop** [comment]
![image](https://user-images.githubusercontent.com/47551949/89377025-8c8b7b80-d723-11ea-8348-dcb7e94fabcf.png)

**Comment by cjloop** [comment]
新的24长度是24，老的是16位。新的是2020年生成的。请核实一下，我们项目目前在用的账号很多，如果ak在新的python环境下不能用的话，可能会很麻烦

**Comment by 824750130** [comment]
如果是AK生成的问题的话 请发工单来解决吧

**Comment by cjloop** [comment]
行吧，ak肯定是没有问题的，一直在用的，怪就怪在为什么老的ak不能这样用呢？

**Comment by cjloop** [comment]
你们服务端的是怎么个加密的。。都是合法的ak，为什么一个可以用，一个不可以用呢？

**Comment by 824750130** [comment]
调用不成功的那串ak 使用其他sdk或者自己调用接口是可以使用的吗？

**Comment by 824750130** [comment]
请问问题已经解决了吗？如果还有问题 可以重新打开。
