### ISSUE TITLE
how to handle foreign region timeout in Aliyun SDK

### ISSUE THREAD

**Issue by maplewf** [aliyun/aliyun-openapi-python-sdk#393]
* **Python Version**:
python 3.6
* **aliyunsdkcore Version**:
2.13.11
* **API**:
aliyun-python-sdk-ecs==4.19.9
aliyun-python-sdk-vpc==3.0.9

Hi,

I'm using Aliyun SDK for manipulating the aliyun resource, but I found that connection timeout frequently happen in API call especially when I operate resource in foreign regions like Frankfurt or Dubai. 

```
ERROR aliyunsdkcore.client [-] HttpError occurred. Host:vpc.eu-central-1.aliyuncs.com SDK-Version:2.13.25 ClientException:SDK.HttpError HTTPConnectionPool(host='vpc.eu-central-1.aliyuncs.com', port=80): Max retries exceeded with url: (Caused by ConnectTimeoutError(<aliyunsdkcore.vendored.requests.packages.urllib3.connection.HTTPConnection object at 0x7fd6477afa90>, 'Connection to vpc.eu-central-1.aliyuncs.com timed out. (connect timeout=5)'))
```

I checked `vpc.eu-central-1.aliyuncs.com` locate in Germany, but my location is in Shanghai, does it mean that it's common problem as long as I do the operation for this kind of region? But it didn't happen when I use Aliyun web page. 

Is there a way for user to send request to the single API endpoint via SDK? And aliyun web service is responsible to distribute these request to different region in internal network. Otherwise, it's hard to use SDK in domestic to operate foreign region.

best regards.

**Comment by 824750130** [comment]
https://github.com/aliyun/aliyun-openapi-python-sdk/blob/master/docs/3-Timeout-EN.md
Please try to set the connect timeout or configure the proxy.
