### ISSUE TITLE
请问如何关掉AcsClient在控制台的debug信息输出？

### ISSUE THREAD

**Issue by WuHaoyang-WHY** [aliyun/aliyun-openapi-python-sdk#401]
* **Python Version**: 3.6
* **aliyunsdkcore Version**:aliyun-python-sdk-core==2.13.4
aliyun-python-sdk-core-v3==2.13.11
* **API**:"filetrans.cn-shanghai.aliyuncs.com"

 
我在调用  from aliyunsdkcore.client import AcsClient 时，控制台会默认输出debug级别的Log信息，请问这个应该怎么设置关闭呢？
![image](https://user-images.githubusercontent.com/45989625/96707834-f7fff380-13ca-11eb-8c1c-ea821f04d65f.png)

我在初始化AcsClient实例的时候传入了debug=False，但似乎不是用来控制这个的，并没有效果。

**Comment by 824750130** [comment]
是否有调用过client的set_stream_logger方法 或设置了名称为aliyunsdkcore的logger？
