### ISSUE TITLE
DomainRecordNotBelongToUser

### ISSUE THREAD

**Issue by jli113** [aliyun/aliyun-openapi-python-sdk#407]
* **Python Version**:3.8.3
* **aliyunsdkcore Version**: 2.6
* **API**:domain

 
The accessKey that I am using has full control, but I got the error.
HTTP Status: 400 Error:DomainRecordNotBelongToUser The DNS record does not exist in your account.

**Comment by 824750130** [comment]
Maybe you can use [Troubleshoot](https://troubleshoot.api.aliyun.com/) to solve the problem.
If you can’t solve it, please submit a ticket.
