### ISSUE TITLE
有没有aliyun-python-sdk-ocr的使用文档

### ISSUE THREAD

**Issue by reesezxf** [aliyun/aliyun-openapi-python-sdk#408]
* **Python Version**:  3.7
* **aliyunsdkcore Version**: 2.13.28
* **API**: aliyun-python-sdk-ocr ：1.0.9
 
有没有aliyun-python-sdk-ocr的使用文档，我使用如下的代码，运行报错
```
from aliyunsdkcore.client import AcsClient
from aliyunsdkocr.request.v20191230.RecognizeIdentityCardRequest import RecognizeIdentityCardRequest
def main():
    idcard_img = r"C:\Users\69107\Desktop\idcard1.jpg"
    idcard_req = RecognizeIdentityCardRequest()
    idcard_req.set_Side("face")
    idcard_req.set_ImageURL(idcard_img)
    # print('url:', idcard_req.get_url("cn-hangzhou", key, sec))
    cli = AcsClient(ak=key, secret=sec, debug=True)
    res = cli.do_action_with_exception(idcard_req)
    print(res)
```
报错信息如下:
aliyunsdkcore.acs_exception.exceptions.ClientException: SDK.HttpError HTTPConnectionPool(host='ocr.cn-hangzhou.aliyuncs.com', port=80): Max retries exceeded with url: /?Version=2019-12-30&Action=RecognizeIdentityCard&Format=JSON&RegionId=cn-hangzhou&Timestamp=2020-11-19T02%3A01%3A23Z&SignatureMethod=HMAC-SHA1&SignatureType=&SignatureVersion=1.0&SignatureNonce=a0c0d03d-a445-5ac1-a533-dcbae07b014c&AccessKeyId=203874928&Signature=7paiLTZlLA2oBEhxa1C%2BfWNosYY%3D (Caused by NewConnectionError('<aliyunsdkcore.vendored.requests.packages.urllib3.connection.HTTPConnection object at 0x0000018BE1D35548>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
通过这个SDK调用的host是ocr.cn-hangzhou.aliyuncs.com， 而阿里云市场给的调用地址是http(s)://dm-51.data.aliyun.com/rest/160601/ocr/ocr_idcard.json

**Comment by JacksonTian** [comment]
云市场的产品不是我们这个。

**Comment by reesezxf** [comment]
> 云市场的产品不是我们这个。

你好，我主要是想使用app key 签名方式调用API,但是找到的示例都是http get的，我用POST方式一直不成功，所以想看看官方的SDK发送POST请求会不会成功
