### ISSUE TITLE
测试分词api报错

### ISSUE THREAD

**Issue by zxyscz** [aliyun/aliyun-openapi-python-sdk#422]
* **Python Version**:
* **aliyunsdkcore Version**:
* **API**:

 
code：
import json
# 这里以分词为例，其它算法的API名称和参数请参考文档
from aliyunsdkalinlp.request.v20200629 import GetWsCustomizedChGeneralRequest
from aliyunsdkcore.client import AcsClient

# 创建AcsClient实例
client = AcsClient(
    "",//自己ak
    ""//自己的ak密码
)
# request = GetWsCustomizedChGeneralRequest.GetWsCustomizedChGeneralRequest()
request = GetWsCustomizedChGeneralRequest.GetWsCustomizedChGeneralRequest()
request.set_Text("云麦好轻智能体脂秤精准蓝牙秤体重测人体脂肪秤家用称健康电子秤")
request.set_OutType("1")
request.set_ServiceCode("alinlp")
request.set_TokenizerId("GENERAL_CHN")
response = client.do_action_with_exception(request)
resp_obj = json.loads(response)
print(resp_obj)

error：

aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 400 Error:UserStatusInvalid The user status is invalid. RequestID: C6095014-53D4-404C-AD66-AE4EA71FA8FC

**Comment by 824750130** [comment]
这是业务异常，可以提交工单解决。
