### ISSUE TITLE
maybe there is a typo

### ISSUE THREAD

**Issue by SCHEN2015** [aliyun/aliyun-openapi-python-sdk#44]
https://github.com/aliyun/aliyun-openapi-python-sdk/blob/8bf812b2b4cf7e05e38ee0809ea9a406f6355617/aliyun-python-sdk-ecs/aliyunsdkecs/request/v20140526/DescribeInstancesRequest.py#L147

Maybe it should be "InstanceId" here, since "aliyuncli ecs DescribeInstances" doesn't support "InstanceIds" as parameter.

**Comment by gaort** [comment]
@SCHEN2015 hi，dear SCHEN2015
thanks for your feedback
this is not a typo, the ecs api “DescribeInstances” requires an optional parameter named "InstanceIds"
you can find the api doc here:
https://help.aliyun.com/document_detail/25506.html?spm=5176.doc25507.6.847.ehJ8NO
