### ISSUE TITLE
aliyun-python-sdk-r-kvstore 包名错误

### ISSUE THREAD

**Issue by pylixm** [aliyun/aliyun-openapi-python-sdk#443]
* **python 3.8**:
* **aliyun-python-sdk-r-kvstore 0.0.1**:

通过`pip install aliyun-python-sdk-r-kvstore` 安装完成后，模块名为 aliyunsdkr-kvstore 而非 aliyunsdkr_kvstore 。

**Comment by Orisdaddy** [comment]
请安装最新版本SDK `pip install aliyun-python-sdk-r-kvstore==2.16.0`
