### ISSUE TITLE
ECS在没有外部IP的情况下，是否能访问到aliyun sdk的endpoint？

### ISSUE THREAD

**Issue by liming01** [aliyun/aliyun-openapi-python-sdk#45]
目前看好像endpoint.xml都是外部的域名。
从测试的角度看，好像在没有外部IP的阿里云实例上，是无法调用对应的SDK进行交互的。
请问是否有办法设置？或者绕过？谢谢！

**Comment by gaort** [comment]
@liming01 您好，这么久才回复您，万分抱歉
SDK在有公共网络的情况下，就可以正常与阿里云API进行交互，这个过程中是不需要外部的独立IP的。

**Comment by liming01** [comment]
谢谢@gaort 的回复，可是从我们的实际的测试来看，在阿里云的虚拟机，如果没有连接EIP或者公共IP的话，都会报调用的SDK对应的服务器无法访问。但是如果加了EIP，就可以访问。所以我怀疑是没有对内网和外网的域名分别尝试导致的。

**Comment by gaort** [comment]
@liming01 感谢您的反馈，我们看下

**Comment by gaort** [comment]
@liming01 
感谢您的反馈，这个的确是我们的问题，十分抱歉给您带来了困扰
可否麻烦您告知我们您想要调用的产品名称，我们会努力推动此事，问题解决后，我们会第一时间在这里回复您。
您目前暂时只能通过添加EIP来访问阿里云的管控API
再次向您道歉，也再次感谢您的反馈

**Comment by baotingfang** [comment]
@gaort @liming01 

我们之前打算调用HAVIP的SDK接口, 实现服务失效的自动切换.  当时的ecs的实例都是处于完全内网的环境. (没有公共IP, 没有EIP, 没有NAT出口), 只有一个内网IP, 我们原以为阿里云可以自动解析内部的SDK endpoint, 但发现没有这样的功能. 

我们使用HAVIP的场景比较特殊: 我们会摘掉自己的eip, 然后挂在到另一台服务器, 在这种情景下, 如果必须要有EIP才可以调用SDK的话, 我们一旦摘掉自己的EIP, 就无法进行后续的SDK调用. 

因此, 期望阿里云在只有内部IP的情况下, 是否也可以调用aliyun的SDK呢?

**Comment by gaort** [comment]
@baotingfang 
感谢您的反馈，这块的确是我们的问题，目前也有团队正在着手处理此事，我会马上将本篇issue反馈给相关的同事。
目前为止，您暂时只能通过有EIP的机器访问管控API，所以建议您可以考虑使用一台挂载了EIP的监控机来控制这个EIP的绑定关系。

**Comment by liming01** [comment]
谢谢@gaort ， 如果解决了，烦劳更新一下这个issue。
再次感谢！

**Comment by gaort** [comment]
@liming01 
不客气，这是我们应该做的。
您也可以使用工单系统来询问类似的问题，并且指定了产品后，能得到对应产品的更详尽的支持。

**Comment by tttwwy** [comment]
@gaort 您好，请问这个问题现在解决了吗? 我现在也遇到了同样的问题。

**Comment by wallisyan** [comment]
@tttwwy 您好？可否告知您使用的具体场景是什么？调用的是哪款产品？

**Comment by tttwwy** [comment]
@wallisyan 您好，具体场景是产品需要每天定时更换ECS服务器的弹性IP，由于只有一台ECS服务器，因此更换操作只能在ECS服务器上进行，步骤如下：
1. 申请新的弹性IP
2. 释放当前ECS服务器弹性IP
3. 给当前ECS服务器绑定新的弹性IP
现在的问题是执行完第2步以后，ECS服务器因为没有外网IP，无法通过外网执行后续的绑定IP操作，因此失败了。这个问题通过工单咨询，也没有得到很好的解决办法。

**Comment by wallisyan** [comment]
您好？目前 SDK只能在公共网络的情况下，才能与阿里云服务进行交互。建议您使用另外一台能连接公网的ECS来操作这台ECS。
