### ISSUE TITLE
Could you please bump `jmespath` to some newer version?

### ISSUE THREAD

**Issue by karajan1001** [aliyun/aliyun-openapi-python-sdk#469]
* **Python Version**: 3.9
* **aliyunsdkcore Version**:  aliyun-python-sdk-core-v3==3.13.31
* **API**: 

 

In https://github.com/iterative/homebrew-dvc/issues/50 we meet an issue when building our project through `homebrew`. It comes from the different dependency of `jmespath`. The `knack ` requires `jmespath==1.0.0` while `aliyun-python-sdk-core-v3` requires `jmespath<1.0.0`. Could you please make `aliyun-python-sdk-core-v3` compatible with a newer version of `jmespath` please? Thank you

-------
当通过`homebrew`安装我们的项目时, 我们遇到了一个依赖兼容问题. `jmespath` 在`knack`(用于`azure`)中要求版本`1.0.0`而`aliyun-python-sdk-core-v3`则要求`<1.0.0`. 请问能否升级`aliyun-python-sdk-core-v3`使其能兼容更新版本的`jmespath`, 谢谢.

**Comment by JacksonTian** [comment]
Please use aliyun-python-sdk-core directly. It's compatible python2/3 both. The aliyun-python-sdk-core-v3 no more update.
