### ISSUE TITLE
我是Python3 安装 缺少 [v20180510]

### ISSUE THREAD

**Issue by Dssssds** [aliyun/aliyun-openapi-python-sdk#477]
![image](https://user-images.githubusercontent.com/17268259/188296355-7366f634-6103-4db2-ba54-03278d98ad28.png)

**Comment by yndu13** [comment]
感谢反馈，我们处理下

**Comment by Dssssds** [comment]
谢谢了。可以帮我看看如何单独安装 v20180510呢， 
我单独安装 pip install alibabacloud_cdn20180510 ，代码引入了，还是不可以的。
有什么办法可以临时处理一下呢？
![image](https://user-images.githubusercontent.com/17268259/188302271-dfb20c43-ebb0-4c1c-92aa-8fd6f0da4a6a.png)

**Comment by yndu13** [comment]
这是引入新的包，使用方式也需要随之改变。调用代码可以参考，https://next.api.aliyun.com/api/Cdn/2018-05-10/RefreshObjectCaches?params={}

**Comment by yndu13** [comment]
或者您可以继续使用老包：aliyun-python-sdk-cdn，将版本退回3.7.1即可，不要使用最新版本3.7.2

**Comment by Dssssds** [comment]
好的，谢谢了。
