### ISSUE TITLE
Update aliyun-python-sdk-core.vendored.requests: 'cgi' is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by amchii** [aliyun/aliyun-openapi-python-sdk#495]
* **Python Version**: 3.11
* **aliyunsdkcore Version**: 2.13.36
* **API**: requests

 
vendored目录下的requests版本旧了，其中引用的cgi包计划在Python 3.13版本移除并已经发出deprecation warning，也就是说Python3.13发布后将会出现ImportError。

**Comment by JacksonTian** [comment]
Closed via #492

**Comment by amchii** [comment]
#492 和此issue无关，此issue提到的cgi在https://github.com/aliyun/aliyun-openapi-python-sdk/blob/master/aliyun-python-sdk-core/aliyunsdkcore/vendored/requests/utils.py 中

**Comment by yndu13** [comment]
Closed via https://github.com/aliyun/aliyun-openapi-python-sdk/pull/513

**Comment by yndu13** [comment]
Closed via https://github.com/aliyun/aliyun-openapi-python-sdk/pull/513
