### ISSUE TITLE
最新release的2.6.0版本，python3装不上

### ISSUE THREAD

**Issue by bangcodes** [aliyun/aliyun-openapi-python-sdk#50]
pypi上面的Requires Python<3啊，这个应该是写错了吧
<img width="500" alt="2017-12-06 10 54 20" src="https://user-images.githubusercontent.com/11722001/33642240-00e8988c-da74-11e7-99f4-1354bb78c25a.png">

**Comment by gaort** [comment]
@bangcodes 
aliyun-python-sdk-core 是用于python2的，python3应该使用aliyun-python-sdk-core-v3
