### ISSUE TITLE
 PyCtypto 已经停止更新 win10上面无法使用

### ISSUE THREAD

**Issue by typ431127** [aliyun/aliyun-openapi-python-sdk#51]
PyCtypto 模块作者已经停止更新，我的版本是3.6但是我在windows上面无法安装sdk，在编译 PyCtypto出现问题
>\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or director
作者已经停止开发了😭😭导致windows上面无法编译成功~~~~
https://github.com/dlitz/pycrypto/issues/173

https://stackoverflow.com/questions/11405549/how-do-i-install-pycrypto-on-windows

**Comment by gaort** [comment]
@typ431127 
谢谢您的反馈，我们会尽快确认这个情况，如果已经停更的话，我们会尽快改为使用其他的解决方案
再次感谢，十分抱歉给您带来了不便

**Comment by gaort** [comment]
@typ431127 
感谢您的耐心等待
我们引入PyCtypto是由于最近新增的一种RSA公私钥的验证方式需要SHA256算法。
我们暂时禁用了windows下的这种验签功能，windows用户可以继续选择AccessKey、STS Token等其他验证方式，非windows用户则不受任何影响。
您可以重试安装最新版的core包，Windows下不会再依赖PyCtypto。
我们后续会继续寻找新的替代方案，以解除上述的使用限制。
再次感谢您的反馈！

**Comment by typ431127** [comment]
谢谢，非常感谢
