### ISSUE TITLE
aliyun-python-sdk-emr 在 python3 中的兼容性问题

### ISSUE THREAD

**Issue by lfzyx** [aliyun/aliyun-openapi-python-sdk#52]
`  File "***/aliyunsdkemr/request/v20160408/CreateExecutionPlanRequest.py", line 79, in set_JobIdLists
    self.add_query_param('JobIdList.' + bytes(i + 1) , JobIdLists[i]);`

`TypeError: Can't convert 'bytes' object to str implicitly`

当然我直接改 CreateExecutionPlanRequest.py 这个文件的 bytes() --> str() 也可以，但还是希望你们解决下

**Comment by gaort** [comment]
@lfzyx
感谢您的反馈:D
您提到的问题，已经在core-v3的2.5.0版本中修复了，您只需使用pip更新下(目前最新版为2.5.5)即可

**Comment by lfzyx** [comment]
我现在用的就是 core-v3 2.5.5 搭配 emr 2.3.1 ，python 是 3.5.3，应该是 emr 的代码需要修改，这段代码中，`'JobIdList.' + bytes(i + 1)`，在任何 python3 的版本中都是会报错的，因为 str 和  bytes 类型不可能拼接

**Comment by gaort** [comment]
@lfzyx 感谢您的反馈
我们会尽快修复这块儿，十分抱歉给您带来的不便

**Comment by gaort** [comment]
fixed
