### ISSUE TITLE
aliyunsdkcore.client AttributeError: "'list' object has no attribute 'get'"

### ISSUE THREAD

**Issue by WormOn** [aliyun/aliyun-openapi-python-sdk#53]
aliyunsdkcore/client.py(282)do_action_with_exception()   request_id = body_obj.get('RequestId'),在body_obj中没有RequestId这个属性，导致程序报 AttributeError: "'list' object has no attribute 'get'"

**Comment by Danceiny** [comment]
写sdk的和写api的小哥没有同步呀~

**Comment by gaort** [comment]
@WormOn @Danceiny 
十分感谢您的反馈以及贡献，相关的PR已经merge ：D

**Comment by WormOn** [comment]
还有就是，咱们的sdk几乎没有说明文档，急用，希望尽快提供一下，谢谢。

**Comment by gaort** [comment]
@WormOn 收到，我们会尽快整理文档到github
目前您可以在官网看到python sdk的使用文档，传送门：
https://help.aliyun.com/document_detail/53090.html?spm=5176.136436.698463.7.608f09d14DOVQZ
