### ISSUE TITLE
为什么是bytes ,str + byte 会报错啊。

### ISSUE THREAD

**Issue by goodking-bq** [aliyun/aliyun-openapi-python-sdk#56]
https://github.com/aliyun/aliyun-openapi-python-sdk/blob/a539d6e268fc07f314c5114c21ced4c8ead51dee/aliyun-python-sdk-ecs/aliyunsdkecs/request/v20140526/CreateInstanceRequest.py#L314

**Comment by lfzyx** [comment]
我也不是很理解这种写法，似乎在 aliyun 的 sdk 中很常见，如 #52

**Comment by gaort** [comment]
@goodking-bq @lfzyx 
感谢您的反馈
这的确是我们的bug，我们会在这周内更新这个bug

**Comment by gaort** [comment]
fixed
