### ISSUE TITLE
获取不到帐号下域名列表

### ISSUE THREAD

**Issue by oudemen** [aliyun/aliyun-openapi-python-sdk#59]
这是我的部分代码：

from aliyunsdkcore.client import AcsClient
from aliyunsdkcore.acs_exception.exceptions import ClientException
from aliyunsdkcore.acs_exception.exceptions import ServerException
from aliyunsdkdomain.request.v20160511 import QueryDomainListRequest

client = AcsClient( 'AccessKeyID','AccessKeySecret‘);
request = QueryDomainListRequest.QueryDomainListRequest()
request.set_PageSize(10)
request.set_PageNum(1)
response = client.do_action_with_exception(request)
print(response) 

最后response返回空：
`
(u'TotalPageNum', 1)
(u'PageSize', 10)
(u'PrePage', False)
(u'CurrentPageNum', 1)
(u'RequestId', u'F95EE320-2694-48EE-8B6A-421FC8CDFAAE')
(u'TotalItemNum', 0)
(u'Data', {u'Domain': []})
(u'NextPage', False)
`
帐号权限已经给到最大了，应该不是权限的问题。也没有爆任何异常，请问是什么问题？

**Comment by gaort** [comment]
@oudemen 
看起来可能是后端服务问题，我们会帮您反馈给相关团队。也建议您提交一个domain产品工单，可以更快速的获得支持

**Comment by gaort** [comment]
@oudemen 
您好，抱歉回复的晚了些，我们帮您咨询了domain服务的相关同学，得知有可能是因为domain目前不支持子账户查询，请您确认下使用的AccessKey是否归属于主账户。
如果没能解决您的问题，您可以在此issue留言，我们会尽快帮您转达。
也建议您可以尝试使用工单，可以更快的得到解决

**Comment by liuzhenwubigboss** [comment]
@gaort 你好，我也遇到了同样的问题。测试通过主账户AccessKey可以正常查询到，但是通过子账户无法查询到。请问是后端做了限制吗？子账户可以很方便地实现权限分配，如果只能通过主账户查询这样是不是失去了子账户的作用呢？
