### ISSUE TITLE
aliyun-python-sdk-ros 存在bug

### ISSUE THREAD

**Issue by Explorer1092** [aliyun/aliyun-openapi-python-sdk#66]
使用 aliyuncli ros DescribeStacks  --RegionId cn-hangzhou 命令提示如下内容
```
{
    "Message": "x-acs-region-id is required.",
    "Code": "RegionIdRequired"
}
Detail of Server Exception:

HTTP Status: 400 Error:RegionIdRequired x-acs-region-id is required. RequestID: None
```
使用 aliyuncli ros DescribeStacks  --RegionId cn-hangzhou-b  命令提示如下

```
{
    "Message": "Can not find endpoint to access.",
    "Code": "SDK.InvalidRegionId"
}
Detail of Client Exception:

SDK.InvalidRegionId Can not find endpoint to access.
```
如果不指定 --RegionId  参数还是会返回第一个错误

**Comment by gaort** [comment]
@Explorer1092 
您好，感谢您的反馈
我们已经发布了新版的aliyuncli，建议您使用新版
https://help.aliyun.com/document_detail/66653.html

**Comment by Explorer1092** [comment]
@gaort 新版仍然有问题

localhost:dev kevin$ aliyun ros GET /stacks
ERROR: [SDK.CanNotResolveEndpoint] Can not resolve endpoint(param = {"Domain":"","Product":"","RegionId":"cn-hangzhou","LocationProduct":"","LocationEndpointType":""}), please check the user guide

**Comment by gaort** [comment]
@Explorer1092 
查一下ROS的API文档，应该会有写API的域名
然后这样调用
aliyun ros GET /stacks --endpoint=xxx.aliyuncs.com

猜测有可能会是ros.aliyuncs.com

**Comment by Explorer1092** [comment]
提示缺少 x-acs-region-id

localhost:dev kevin$ aliyun ros GET /stacks --endpoint=ros.aliyuncs.com --RegionId=hangzhou
ERROR: SDK.ServerError 400 Bad Request {"Message": "x-acs-region-id is required.", "Code": "RegionIdRequired"}
如何这header里设置 x-acs-region-id？

https://help.aliyun.com/document_detail/28904.html?spm=a2c4g.11186623.6.573.ui9gAB

**Comment by Explorer1092** [comment]
localhost:dev kevin$ aliyun ros GET /stacks --endpoint=ros.aliyuncs.com --region=hangzhou
ERROR: SDK.ServerError 400 Bad Request {"Message": "x-acs-region-id is required.", "Code": "RegionIdRequired"}

**Comment by gaort** [comment]
@Explorer1092 
感谢您的反馈，这个有可能是我们的bug，我们会仔细研究下
目前有一个workaround：
aliyun ros GET /stacks --endpoint=ros.aliyuncs.com --RegionId=hangzhou1 --header x-acs-region-id=cn-hangzhou
