### ISSUE TITLE
Question: Why is aliyun-mns not part of this repo?

### ISSUE THREAD

**Issue by smetj** [aliyun/aliyun-openapi-python-sdk#67]
Dear sir, madam,

Is there any reason https://github.com/gikoluo/aliyun-mns is not part of this repository? Or is there another library advised to use for https://www.alibabacloud.com/product/message-service ?

Many thanks,

Sincerely,

- J.S.

**Comment by gaort** [comment]
@smetj 
Because the service scenario of MNS is rather special, the current Alibaba Cloud unified OpenAPI gateway cannot support it.
This repository is the SDK of Alibaba Cloud unified OpenAPI gateway. MNS does not have an access to 
 the gateway, so the SDK will be different.

**Comment by smetj** [comment]
@gaort Tnx for the feedback. Much appreciated.
