### ISSUE TITLE
11771185 钉钉群显示无法找到该用户

### ISSUE THREAD

**Issue by chensixiu** [aliyun/aliyun-openapi-python-sdk#68]
![image](https://user-images.githubusercontent.com/26560870/37336672-1739336a-26ed-11e8-916a-864a41cc6ab0.png)

**Comment by gaort** [comment]
这个看起来是添加用户为好友，和进群的入口可能不同，您再找找看
群本身是木有问题的，已经接近200用户了：D
或者直接issue提问也是可以的
