### ISSUE TITLE
sts:GetCallerIdentity not implemented?

### ISSUE THREAD

**Issue by JokerQyou** [aliyun/aliyun-openapi-python-sdk#7]
There is only `AssumeRoleRequest` in sts SDK, but I did see `GetCallerIdentity` API in [STS API documentation][1]. When will this get implemented in the Python SDK?

[1]: https://help.aliyun.com/document_detail/43767.html

**Comment by gaort** [comment]
Thank you for post this issue, this API has been supported, we're very sorry for late response.
