### ISSUE TITLE
ROS中DescribeResourcesRequest类返回类型错误及请求参数问题.

### ISSUE THREAD

**Issue by idoop** [aliyun/aliyun-openapi-python-sdk#74]
# 运行环境: 
> - python 3.6
> - windows10 & ubuntu 16

# 错误重现:

``` python
from aliyunsdkros.request.v20150901 import DescribeResourcesRequest

    def get_resources(self,stackId=None,stackName=None)->dict:
        '''
        查询某个资源栈的资源列表
        :param stackId:  栈ID
        :param stackName: 栈名
        :return:
        '''
        req = DescribeResourcesRequest.DescribeResourcesRequest()
        if stackId:
            req.set_StackId(StackId=stackId)
        if stackName:
            req.set_StackName(StackName=stackName)
        resp = json.loads(self.client.do_action_with_exception(req).decode())
        return resp
```

## 错误 1

根据 [官方API文档说明](https://help.aliyun.com/document_detail/28916.html?spm=a2c4g.11186623.6.587.qGfy2a),这里的`StackID`和`StackName`为非必要参数,可不填.但是在我留空提交后，报了如下错误:

>File "C:\Program Files\Python36\lib\site-packages\aliyunsdkcore\client.py", line 279, in do_action_with_exception
    request_id=request_id)
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 400 Error:InvalidUrl Request url is invalid, Illegal character in path at index 38: http://ros.aliyun-inc.com:8080/stacks/[StackName]/[StackId]/resources RequestID: D917A6C0-8EA6-424F-BC90-32C84E9E0020

这里为什么又要StackId和StackName参数？

## 错误 2

给了StackId和StackName参数,但有如下错误:
>   File "C:\Program Files\Python36\lib\site-packages\aliyunsdkcore\client.py", line 266, in do_action_with_exception
    request_id = body_obj.get('RequestId')
AttributeError: 'list' object has no attribute 'get'

该返回的类型为list,并非dict.还请及时修正。

**Comment by gaort** [comment]
@idoop  感谢反馈
错误1的确是文档存在问题，已帮您转达给ROS产品线，这两个参数是必填的。
错误2建议您更新下core包，也有可能是资源编排服务未能返回RequestId导致的，我会帮您尽快确认。

**Comment by idoop** [comment]
@gaort `aliyun-python-sdk-core-v3` 用的是pypi官方下的最新的`2.8.6`，但这Github仓库上最新的是`2.8.5`.
