### ISSUE TITLE
ROS中DescribeStacksRequest与DeleteStackRequest类请求RegionId参数问题.

### ISSUE THREAD

**Issue by idoop** [aliyun/aliyun-openapi-python-sdk#75]
# 运行环境: 
> - python: `3.6`
> - windows: `10` & ubuntu: `16`
> - aliyun-python-sdk-core-v3: `2.8.6` 
> - aliyun-python-sdk-ros: `2.2.7`

# 错误重现:
以DescribeStacksRequest类举例,DeleteStackRequest也是相同问题.
``` python
from aliyunsdkros.request.v20150901 import DescribeStacksRequest
    def get_stacks(self,regionId='cn-shenzhen',stackId=None,status=None,name=None):
        '''
        查询资源栈列表
        :param stackId: 资源栈 ID
        :param status: 用于过滤的资源栈状态。
        :param name: 资源栈名称
        :return:
        '''
        client = aliyunsdkcore.client.AcsClient(ak=self.ak,secret=self.secret,region_id=regionId)
        req = DescribeStacksRequest.DescribeStacksRequest()
        if stackId:
            req.set_StackId(StackId=stackId)
        if status:
            req.set_Status(Status=status)
        if name:
            req.set_Name(Name=name)
        req.set_PageSize(self.pagesize)
        resp = json.loads(client.do_action_with_exception(req).decode())
        return resp
```

## 错误
>   File "C:\Program Files\Python36\lib\site-packages\aliyunsdkcore\client.py", line 279, in do_action_with_exception
    request_id=request_id)
aliyunsdkcore.acs_exception.exceptions.ServerException: HTTP Status: 400 Error:RegionIdRequired x-acs-region-id is required. RequestID: None

其实已给出RegionId,但即使在add_query_params方法中单独指定,也是相同错误,提示无regionId,可若使用add_header(k='x-acs-region-id',v='cn-shenzhen')方法则通过.

**Comment by jxyowen** [comment]
感谢反馈，下个版本会修复
