### ISSUE TITLE
Cannot use AcsClient in "with .. as" construction

### ISSUE THREAD

**Issue by ivladdalvi** [aliyun/aliyun-openapi-python-sdk#77]
`AcsClient` does not have `__exit__` attribute and hence cannot be used in "with .. as" block. This example code

```python
from aliyunsdkcore.client import AcsClient
with AcsClient('key', 'secret', 'region') as client:
  print client
```

will produce error `AttributeError: AcsClient instance has no attribute '__exit__'`.

Solution would be to implement support for "with" in accordance with [PEP343](https://www.python.org/dev/peps/pep-0343/).

**Comment by jxyowen** [comment]
Thanks a lot and we will fix this in next version

**Comment by Qingtang-SDK** [comment]
No actual  __exit__ logic needed for AcsClient. So we won't enable 'with' clause for it. Thanks for your feedback.
