### ISSUE TITLE
core里面，CommonRequest请求redis的性能监控指标，MonitorKey里面没有Cpu的相关指标，其他都有

### ISSUE THREAD

**Issue by sunmenglin** [aliyun/aliyun-openapi-python-sdk#80]
core里面，CommonRequest请求redis的性能监控指标，MonitorKey里面没有Cpu的相关指标，其他都有

**Comment by Qingtang-SDK** [comment]
这是产品层面的问题。请查阅相关API文档，或者发工单联系我们解决。谢谢。

**Comment by xuebinshushu** [comment]
> core里面，CommonRequest请求redis的性能监控指标，MonitorKey里面没有Cpu的相关指标，其他都有

可以试用cms云监控进行获取,同时请教: core里的CommonRequest在哪里,没找到, 我也在获取redis指标,只能获取到InstanceId,不能获取到别名

**Comment by sunmenglin** [comment]
> > core里面，CommonRequest请求redis的性能监控指标，MonitorKey里面没有Cpu的相关指标，其他都有
> 
> 可以使用cms云监控进行获取,同时请教: core里的CommonRequest在哪里,没找到, 我也在获取redis指标,只能获取到InstanceId,不能获取到别名

CommonRequest在request.py里面。redis的实例信息可以通过aliyunsdkr_kvstore的request里的DescribeInstancesRequest获取
