### ISSUE TITLE
aliyun-python-sdk-core-v3==2.8.8 CommonRequest.add_query_param参数无效

### ISSUE THREAD

**Issue by lcwangchao** [aliyun/aliyun-openapi-python-sdk#83]
看代码貌似 `CommonRequest` 在生成内部 `RpcRequest` 的时候没有 `add_query_param` , 只是设置了 `set_uri_params` 但是这两个设置的不是一个内部变量，无法生成正确的url

**Comment by jxyowen** [comment]
感谢反馈，会尽快修复
