### ISSUE TITLE
aliyun-python-sdk-core-v3==2.8.9 use python2 code module httplib

### ISSUE THREAD

**Issue by idoop** [aliyun/aliyun-openapi-python-sdk#84]
pip 安装 `aliyun-python-sdk-core-v3` [latest version](https://pypi.org/project/aliyun-python-sdk-core-v3/) **2.8.9**, 在导入该库使用后，报了错不存在`httplib`模块的错误，而`httplib`是python2的库。
看样子是没单元测试就发布了。

**Comment by jxyowen** [comment]
您好，aliyun-python-sdk-core-v3 并没有引用httplib
