### ISSUE TITLE
python sdk问题

### ISSUE THREAD

**Issue by tonycat2018** [aliyun/aliyun-openapi-python-sdk#88]
windows server 2008 R2系统的ECS，安装python V3.6.5，使用pip install aliyun-python-sdk-core-v3安装python sdk

安装完成后，使用RAM角色认证方式，调测过程中发现在ecs_ram_role_singer.py文件第58行存在问题：
response = json.loads(content.**deconde**('utf-8'))

-- 上面deconde拼写错误，应该是decode

**Comment by Qingtang-SDK** [comment]
感谢反馈，该问题已经在最新版本解决。
