### ISSUE TITLE
当'body_obj' 为List时，body_obj.get报错，这里的except无法捕捉错误

### ISSUE THREAD

**Issue by Dreamheart** [aliyun/aliyun-openapi-python-sdk#89]
https://github.com/aliyun/aliyun-openapi-python-sdk/blob/6b9eb1c005b79aab8dae70e504f1b1cfc3284064/aliyun-python-sdk-core/aliyunsdkcore/client.py#L262

建议修改为：
except (ValueError, TypeError, AttributeError):

**Comment by jxyowen** [comment]
谢谢反馈。问题将在下个版本修复

**Comment by wallisyan** [comment]
谢谢您的反馈，这个问题在aliyun-python-sdk-core 2.11.4版本已经修复。
