### ISSUE TITLE
无法使用ECS_RAM_ROLE

### ISSUE THREAD

**Issue by zhouwenb** [aliyun/aliyun-openapi-python-sdk#90]
aliyun-openapi-python-sdk/aliyun-python-sdk-core/aliyunsdkcore/auth/signers/ecs_ram_role_singer.py

49行，self._expiration实际读到的是个时间字符串，会报异常：
`
    def _check_session_credential(self):
        now = int(time.time())
        if now - self._last_update_time > (self._expiration * self._REFRESH_SCALE):
            self._refresh_session_ak_and_sk()
`

**Comment by wallisyan** [comment]
Hi, this bug has been fixed in our newest version, please update your aliyun-python-sdk-core and try again. Thank you, and have a good day!
