### ISSUE TITLE
aliyun-python-sdk-core/aliyunsdkcore/http/http_response.py 使用 httplib 导致线程不安全

### ISSUE THREAD

**Issue by crhan** [aliyun/aliyun-openapi-python-sdk#95]
httplib 线程不安全, 详见 https://stackoverflow.com/questions/5825151/are-urllib2-and-httplib-thread-safe

复现方法:

1. 使用 concurrent.futures.ThreadPoolExecutor, 使用同一个 acs_client, 调用 do_action_with_exception
2. 在 aliyun-python-sdk-core/aliyunsdkcore/http/http_response.py:105 打日志, 输出 id(response)

会发现存在碰撞的情况

![image](https://user-images.githubusercontent.com/532040/42874281-4730a560-8ab3-11e8-92c0-e5447caee67b.png)

**Comment by Qingtang-SDK** [comment]
您好，目前Python SDK使用的网络库已经从http.client更换成了requests，线程不安全的问题已经解决。感谢您的反馈。
